### ISSUE TITLE
spark-operator (v1.0) failed to install sparkapplications CRD

### ISSUE THREAD

**Issue by dynofu** [kubeflow/manifests#1005]
https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_istio_dex.v1.0.1.yaml

```
 - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: spark/spark-operator
    name: spark-operator
```

after kfctl apply, kubeflow installation seems successful but the crds of
``` 
scheduledsparkapplications.sparkoperator.k8s.io                                                                                                                                       
sparkapplications.sparkoperator.k8s.io
```
are missing.  use 
```
 kustomize build spark-operator/overlays/application/ | kubectl apply -f -
```
seems to have bring the crd back,

not sure if there is a race condition between these resources,
```
resources:
- spark-sa.yaml
- cr-clusterrole.yaml
- crb.yaml
- crd-cleanup-job.yaml
- deploy.yaml
- operator-sa.yaml
- role.yaml
- rolebinding.yaml
- sparkapplications.sparkoperator.k8s.io-crd.yaml
- scheduledsparkapplications.sparkoperator.k8s.io-crd.yaml
```
https://github.com/kubeflow/manifests/blob/master/spark/spark-operator/base/kustomization.yaml#L27
