### ISSUE TITLE
spark-operator (v1.0) failed to report application status

### ISSUE THREAD

**Issue by dynofu** [kubeflow/manifests#1006]
https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_istio_dex.v1.0.1.yaml

```
 - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: spark/spark-operator
    name: spark-operator
```
after workaround #1005 , it seems to be working, but it looks like it does not report 
`status.Application.state` thus even the spark application has succeeded, spark-operator has no idea of the status. 

https://github.com/kubeflow/manifests/blob/master/spark/spark-operator/base/sparkapplications.sparkoperator.k8s.io-crd.yaml

diff with upstream 

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/manifest/crds/sparkoperator.k8s.io_sparkapplications.yaml

it's like a lot has happened.
the part that catch my eye is the missing of the status  

```
+  subresources:
+    status: {}
```

i think it needs to catch up with the upstream.
