### ISSUE TITLE
jupyter-web-app fails with kustomize build for aws overlay

### ISSUE THREAD

**Issue by apryiomka** [kubeflow/manifests#1182]
```
Error: accumulating resources: recursed merging from path 'manifest/kustomize/jupyter-web-app/overlays/aws': may not add resource with an already registered id: rbac.authorization.k8s.io_v1_ClusterRoleBinding|~X|jupyter-web-app-cluster-role-binding
```

**Comment by apryiomka** [comment]
It seems like aws overlay is causing this error...

**Comment by Jeffwan** [comment]
@apryiomka 

Are you testing master? Can you delete `aws` overlay at this moment and have another try?

**Comment by apryiomka** [comment]
@Jeffwan , i am not testing master, i am trying to get KFServing fix with master. Since it is not tagged to any release, i have no choice but to deploy master. Removing `aws` overlay does seem to solve the issue. My best guess it is related to this bug in kustomize: https://github.com/kubernetes-sigs/kustomize/issues/1251

**Comment by Jeffwan** [comment]
> @Jeffwan , i am not testing master, i am trying to get KFServing fix with master. Since it is not tagged to any release, i have no choice but to deploy master. Removing `aws` overlay does seem to solve the issue. My best guess it is related to this bug in kustomize: [kubernetes-sigs/kustomize#1251](https://github.com/kubernetes-sigs/kustomize/issues/1251)

em. master components have been refactored but it's still using base rather than base_v3 in this case. I have not looked into details yet. AWS overlay was added recently that's why I suggest to remove and see it's working or not. If original kfdef doesn't work, then it could be kustomize issue

**Comment by PatrickXYS** [comment]
The reason why this fails:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
configMapGenerator:
- name: jupyter-web-app-config
  behavior: replace
  files:
  - spawner_ui_config.yaml
```

We need to change this into:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
configMapGenerator:
- name: jupyter-web-app-config
  behavior: replace
  files:
  - spawner_ui_config.yaml
```

Otherwise, it will re-deploy `../../base` resources. 

But this change induces another issue, I'll keep updated.
