### ISSUE TITLE
[GCP] Persistent disk name for mysql PV isn't valid

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#1294]
I tried deploying with GCP blueprints from master. I get the following error

```
Error from server (Forbidden): error when creating ".build/kubeflow-apps/~g_v1_persistentvolume_mysql-pv.yaml": persistentvolumes "mysql-pv" is forbidden: error querying GCE PD volume dls-kf-storage-metadata-store: disk is not found
```

Here is the contents of `~g_v1_persistentvolume_mysql-pv.yaml`

```
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: mysql
    app.kubernetes.io/component: mysql
    app.kubernetes.io/name: mysql
  name: mysql-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  gcePersistentDisk:
    fsType: ext4
    pdName: dls-kf-storage-metadata-store
```

@Bobgy How is this supposed to work? How is the PD supposed to get created? Are we using Kubernetes to create the disk? If its created outside of K8s then we probably need a CNRM resource 

The name `dls-kf-storage-metadata-store` also looks problematic as it doesn't look like it would be unique for different deployments.

/assign @Bobgy
