### ISSUE TITLE
[AWS] Multi-user pipelines doesn't work for AWS

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/manifests#1430]
There're few things needs to be changed. 

1. Pipeline central dashboard return `upstream connect error or disconnect/reset before headers. reset reason: connection failure` which looks at some restrictions on the istio side due to misconfiguration?

I use debug pod pod and seem I am able to fetch pipelines and UI.  Need to find more clues on this issue. Working on it.

2. Python SDK uses http client doesn't work as well. 

3. Need to override header and prefix in `ml-pipeline-ui-artifact`

```
  gkeMetadata: { disabled: false },
  auth: {
    enabled: false,
    kubeflowUserIdHeader: 'x-goog-authenticated-user-email',
    kubeflowUserIdPrefix: 'accounts.google.com:'
  }
```

/cc @PatrickXYS

**Comment by Jeffwan** [comment]
Problem is below, it should mount volumes and read the values.  There's a problem that only `kubeflow-config` has the `userid-header` and `userid-prefix`. Since configmaps can not be shared across namespaces..This is something we need to improve in the future.. Either use plain txt as env value or replica some info into end user's namespace. 

https://github.com/kubeflow/manifests/blob/dcfc9f2a04854ba2bd7762df6981088f96d9684f/pipeline/installs/multi-user/pipelines-profile-controller/sync.py#L184-L226



Steps to fix artifact.

1. configmap
```
1. kubectl get configmap kubeflow-config -n kubeflow --export -o yaml | kubectl apply -n admin -f -

2. kubectl edit deployment ml-pipeline-ui-artifact -n admin

3. Add envs.

       env: 
        - name: KUBEFLOW_USERID_HEADER
          valueFrom:
            configMapKeyRef:
              name: kubeflow-config
              key: userid-header
        - name: KUBEFLOW_USERID_PREFIX
          valueFrom:
            configMapKeyRef:
              name: kubeflow-config
              key: userid-prefix

```


2. plain text
