### ISSUE TITLE
Add VirtualService to allow GCLB health checks and get rid of backend updater statefulset

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#1467]
We currently use this stateful set as a hack to set the health check for the GCLB
https://github.com/kubeflow/manifests/tree/b3f5b41780a01845619884e638f4f6c9183d8fef/gcp/iap-ingress/base

It looks like there is now a better approach based on creating a virtual service which will just match the health check requests and reroute them to the readiness probe.
https://cloud.google.com/solutions/integrating-https-load-balancing-with-istio-and-cloud-run-for-anthos-deployed-on-gke

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: health  
spec:
  gateways:
  - istio-system/ingressgateway
  hosts:
  - "*"
  http:
  - match:
    - headers:
       user-agent:
         prefix: GoogleHC
      method:
       exact: GET
      uri:
        exact: /
    rewrite:
      authority: istio-ingressgateway.istio-system.svc.cluster.local:15020
      uri: /healthz/ready
    route:
    - destination:
        host: istio-ingressgateway.istio-system.svc.cluster.local
        port:
          number: 15020
```

I tried it and it works. 

Getting rid of the backend-updater pod should improve reliability; we've had various flakiness issues related to the healthcheck not getting set correctly.
