### ISSUE TITLE
unknown field "env" in v1alpha1.ProxyConfig

### ISSUE THREAD

**Issue by mcantrell** [kubeflow/manifests#1490]
Running through the GCP getting started guide:

https://www.kubeflow.org/docs/gke/deploy/deploy-cli/#deploy-kubeflow

Running the make-apply step produces the following error:

```
make apply
# Delete build because we want to prune any resources which are no longer defined in the manifests
rm -rf .build/
mkdir -p .build/
PROJECT=project-xxx NAME=project-xxx ./hack/check_domain_length.sh
./hack/check_oauth_secret.sh
# ***********************************************************************************
# Hydrate cnrm
mkdir -p .build/gcp_config
kustomize build --load_restrictor none -o .build/gcp_config ./instance/gcp_config
#************************************************************************************
# hydrate asm
istioctl manifest generate -f ./upstream/manifests/gcp/v2/asm/istio-operator.yaml -o .build/istio
Error: validation errors (use --force to override):
unknown field "env" in v1alpha1.ProxyConfig
make: *** [hydrate-asm] Error 1
```

Contents of ./upstream/manifests/gcp/v2/asm/istio-operator.yaml

```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  clusterName: "project-xxx/us-central1/project-xxx" # {"$kpt-set":"asm-cluster-name"}
spec:
  profile: asm
  hub: gcr.io/gke-release/asm
  tag: 1.4.7-asm.0
  values:
    gateways:
      istio-ingressgateway:
        type: NodePort
    global:
      meshID: "project-xxx_us-central1_project-xxx" # {"$kpt-set":"asm-mesh-id"}
      trustDomain: "project-xxx.svc.id.goog" # {"$kpt-set":"identity-ns"}
      sds:
        token:
          aud: "project-xxx.svc.id.goog" # {"$kpt-set":"identity-ns"}
      proxy:
        env:
          GCP_METADATA: "project-xxx|282680672241|project-xxx|us-central1" # {"$kpt-set":"asm-gcp-metadata"}
    nodeagent:
      env:
        GKE_CLUSTER_URL: "https://container.googleapis.com/v1/projects/project-xxx/locations/us-central1/clusters/project-xxx" # {"$kpt-set":"asm-cluster-url"}
```
