### ISSUE TITLE
SHA Digest used in knative-install

### ISSUE THREAD

**Issue by connorlwilkes** [kubeflow/manifests#1521]
It appears that knative-install is using a SHA digest for ref to Docker image rather than a tag. This makes it more difficult to mirror the images across to private repo as you SHA digest will change once image is pulled and then pushed across into private repo. Moreover it appears to break kfctl alpha set-image for some reason also. Instead I would suggest we use tags, upon investigation it would appear that the current digest being used relates to: v.0.11.1 for all knative images.

```
`apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knative-serving
resources:
- gateway.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- service-role.yaml
- service-role-binding.yaml
- role-binding.yaml
- config-map.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
- apiservice.yaml
- image.yaml
- hpa.yaml
- webhook-configuration.yaml
commonLabels:
  kustomize.component: knative
images:
- name: gcr.io/knative-releases/knative.dev/serving/cmd/activator
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/activator
  digest: sha256:c51023e62e351d5910f92ee941b4929eb82539e62636dd3ccb4a016d73e86b2e
- name: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler-hpa
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler-hpa
  digest: sha256:75da5ff75bc1e71799d039846b1bbd632343894c88feaa59914cfeeb1b213c81
- name: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  digest: sha256:998a405454832cda18a4bf956d26d610a2df2130a39b834b597a89a3153c8c15
- name: gcr.io/knative-releases/knative.dev/serving/cmd/networking/istio
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/networking/istio
  digest: sha256:61461fa789e19895d7d1e5ab96d8bb52a63788e0607e1bd2948b9570efeb6a8f
- name: gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  digest: sha256:d07560cd5548640cc79abc819608844527351f10e8b0a847988f9eb602c18972
- name: gcr.io/knative-releases/knative.dev/serving/cmd/controller
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/controller
  digest: sha256:1e77bdab30c8d0f0df299f5fa93d6f99eb63071b9d3329937dff0c6acb99e059`
```

Unsure if this issue occurs in any other of the kustomize.yamls, I only came across this one due to my current configuration. Simple fix would be to change to:

```
`images:
- name: gcr.io/knative-releases/knative.dev/serving/cmd/activator
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/activator
  tag:  v0.11.1
- name: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler-hpa
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler-hpa
  tag:  v0.11.1
- name: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  tag: v0.11.1
- name: gcr.io/knative-releases/knative.dev/serving/cmd/networking/istio
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/networking/istio
  tag:  v0.11.1
- name: gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  tag: v0.11.1
- name: gcr.io/knative-releases/knative.dev/serving/cmd/controller
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/controller
  tag: v0.11.1`
```
