### ISSUE TITLE
kubeflow deploy fail error gzip: invalid header  filename="kfconfig/types.go:524"

### ISSUE THREAD

**Issue by danasaur** [kubeflow/manifests#1545]
Running on EKS with cloud9

I went step by step exactly through the following three tutorials:

https://www.eksworkshop.com/020_prerequisites/
https://www.eksworkshop.com/030_eksctl/
https://www.eksworkshop.com/advanced/420_kubeflow/

got to https://www.eksworkshop.com/advanced/420_kubeflow/install/ 

$ kfctl apply -V -f ${CONFIG_FILE}

<img width="1196" alt="Screen Shot 2020-09-05 at 5 22 08 PM" src="https://user-images.githubusercontent.com/320703/92347920-46a93680-f086-11ea-8ead-71d019e57cc0.png">

I tested that I am able to manually extract the folder contents with:

$ curl -L https://github.com/kubeflow/manifests/archive/v1.0.1.tar.gz > test.tgz

$ tar zxvf test.tgz

**Comment by sakaia** [comment]
I hope this kind of workaround is supported (kfctl: support relative local repos in config #3712)[https://github.com/kubeflow/kubeflow/issues/3712]

**Comment by sakaia** [comment]
For my workaround, I make web server as a workaround and works.
Download file 

```
curl -L https://github.com/kubeflow/manifests/archive/v1.0.2.tar.gz
```

On deployment server

```
python3 -m http.server 8082
```

Edit kfctl_k8s_istio.v1.0.2.yaml

```yaml
  repos:
  - name: manifests
    #uri: https://github.com/kubeflow/manifests/archive/v1.0.2.tar.gz
    uri: http://127.0.0.1:8082/manifests-1.0.2.tar.gz
  version: v1.0.2
status:
```
