### ISSUE TITLE
What's the proper convention for customizing kubeflow in a maintainable way?

### ISSUE THREAD

**Issue by mttcnnff** [kubeflow/manifests#1549]
I understand that you can use kfctl to generate kustomization.yaml files and then edit the generated files in the /kustomize directory but this doesn't seem maintainable as if I rerun kfctl it will overwrite that /kustomize directory, which could be a problem when you want to change the upstream repo from which you pull config for something like an upgrade down the road.

Is there anyway to generate the overall config for the kubeflow deploy using kfctl but to refer to outside kustomize files that wouldn't get thrown out from a rerun?  This way I would have my "base deploy" and then my custom configuration and resources on top?

**Comment by Bobgy** [comment]
@mttcnnff This is exactly the reason why we built kubeflow/gcp-blueprint.
Some explanation in https://github.com/kubeflow/gcp-blueprints/issues/123.

GCP is now the only platform following this pattern. I'm interested if other platforms want to follow.

**Comment by mttcnnff** [comment]
@Bobgy Can you explain a bit more of how this pattern works? I'm on AWS but more than happy to contribute to get this in a better place

**Comment by thesuperzapper** [comment]
I make use of argo-cd.

**Here is what I do:**
1. create a private git repo (for all the following steps)
1. use `kfctl` to generate the top-level `kubeflow/xxx/kustomization.yaml` files which reference, `.cache/manifests-1.1-branch/...`.
1. create yaml patch files with the changes I need for my cluster (like dex `config.yaml` ConfigMap)
1. add these yaml to the corresponding  `kustomization.yaml` under `resources:`, so they get strategic merged in by kustomize
1. create an argo-cd Application which targets each of these top-level folders 
    * example: `GIT_ROOT/kubeflow/kubeflow-apps/kustomization.yaml`
    * note: remember to set `kustomize.buildOptions: --load_restrictor=none` in your argo-cd configmap


This has the benefit of being git-ops, and means I can make any changes I need without modifying the files in `.cache/*` directly. It also means I can easily remove components which are already on my K8S cluster, like `istio` and `cert-manager`.

If there is interest, I can put a guide for this on the main Kubeflow docs, as I expect this approach is probably the most generic way to deploy kubeflow if you are not wanting to use one of the vendor's approaches.

**Comment by mttcnnff** [comment]
@thesuperzapper this sounds good, at the end of the day you're using kfctl once to generate everything and then from there on using kustomize? Never to run kfctl again?

**Comment by thesuperzapper** [comment]
@mttcnnff yep, you only use `kfctl` once per major Kubeflow version (which is important for git-ops, as you should be storing exactly the YAML you expect to be in your cluster, explicitly in your repository).

Because the purpose of having multiple environments is usually testing dev/prod, I would recommend having completely seperate folders under a repo to store the `./kustomize/` folders for each environment. 

## Kubeflow app-of-apps:
The basic structure is a single repo with a helm chart at its root. This outer chart is an app-of-apps which deploys the various sub kubeflow apps found in the `./kustomize/` folder generated by `kfctl`.

Repo structure for `kubeflow-app-of-apps`:
* `./dev`
   * `./.cache`
      * `...`
   * `./kuztomize`
      * `./kubeflow-apps`
         * `kustomization.yaml`
         * `YOUR_PATCH.yaml`
      * `...`
* `./prod`
   * `./.cache`
      * `...`
   * `./kuztomize`
      * `...`
* `./templates`
   * `./argocd-apps.yaml`
   * `./validate-input.tpl`
* `Chart.yaml`
* `values.yaml`

### `./templates/argocd-apps.yaml`

```yaml
{{- /*
While this looks complex, it simply:
  1. Loops over each kustomize folder under the requested `environment` sub-folder.
  2. Reads the corresponding kustomization.yaml file, interpreting it as a YAML structure.
     (This lets us extract the namespace field in the following step.)
  3. Creates a new Argo-CD Application Resource for each one it finds.
*/ -}}
{{ $search_path := printf "%s/kustomize/*/kustomization.yaml" .Values.environment }}
{{- range $file_path, $bytes := .Files.Glob $search_path }}
{{- $folder_path := dir $file_path }}
{{- $chart_name := base $folder_path }}
{{- $kustomize_yaml := $.Files.Get $file_path | fromYaml }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.argo.app_of_apps.name }}--{{ $chart_name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $kustomize_yaml.namespace | default "kubeflow" }}
    server: https://kubernetes.default.svc
  source:
    path: {{ $folder_path | quote }}
    repoURL: {{ $.Values.argo.app_of_apps.repo.url | quote }}
    targetRevision: {{ $.Values.argo.app_of_apps.repo.target_revision | quote }}
  project: default
  ignoreDifferences:
    # kubeflow has many empty `/descriptor` fields, which are removed in the live manifest
    # NOTE: as the `/descriptor` field doesn't do much, we can just ignore the diffs they create
    - group: app.k8s.io
      kind: Application
      jsonPointers:
        - /spec/descriptor
    # kubeflow uses role aggregation so the `/rules` field changes in the live manifest
    # NOTE: this could cause some issues for ClusterRole not using aggregation
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jsonPointers:
        - /rules
---
{{- end }}
```

### `./templates/validate-input.tpl`

```yaml
{{ $valid_environments := list "dev" "prod" }}
{{ if not (has .Values.environment $valid_environments) }}
  {{ fail "VALUE: 'environment' must be one of: ['dev','prod']" }}
{{ end }}

{{ if empty .Values.argo.app_of_apps.name }}
  {{ fail "VALUE: 'argo.app_of_apps.name' is required!" }}
{{ end }}

{{ if empty .Values.argo.app_of_apps.repo.url }}
  {{ fail "VALUE: 'argo.app_of_apps.repo.url' is required!" }}
{{ end }}

{{ if empty .Values.argo.app_of_apps.repo.target_revision }}
  {{ fail "VALUE: 'argo.app_of_apps.repo.target_revision' is required!" }}
{{ end }}
```

### `./Chart.yaml`

```yaml
apiVersion: v2
name:  kubeflow-apps
version: 1.1.0
```

### `./values.yaml`

```yaml
# this must be set by argo-cd as 'dev' or 'prod'
environment: null

argo:
  app_of_apps:
    # the name of the argo-cd app which targets the root of this repo
    # Build Env: $ARGOCD_APP_NAME
    # Example: `kubeflow-apps`
    name: null

    repo:
      # the URL of THIS repo
      # Build Env: $ARGOCD_APP_SOURCE_REPO_URL
      # Example: `ssh://git@example.org/kubeflow-apps.git`
      url: null

      # the desired target revision of THIS repo
      # Build Env: $ARGOCD_APP_SOURCE_TARGET_REVISION
      # Example: `master` or `v1.1.0`
      target_revision: null
```

## argo-cd app which targets `kubeflow-app-of-apps`

* for `prod` you will see I am targeting the `v1.1.0` Git tag, which you must create on your `kubeflow-app-of-apps` repo
* for `dev` I would usually set `targetRevision` to `master`, so that people can make changes without creating a new tag


```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: "."
    repoURL: ssh://git@example.org/kubeflow-apps.git
    targetRevision: v1.1.0
    helm:
      parameters:
        - name: environment
          value: prod
        # as this is an app-of-apps, and the inner-apps are also in the same repo
        # we ensure all repos/target_revisions are the same, by passing them here
        - name: argo.app_of_apps.repo.url
          value: $ARGOCD_APP_SOURCE_REPO_URL
        - name: argo.app_of_apps.repo.target_revision
          value: $ARGOCD_APP_SOURCE_TARGET_REVISION
        # similar to the repo values: we pass the name of this app, so it can be used in the name of the child apps
        - name: argo.app_of_apps.name
          value: $ARGOCD_APP_NAME
  project: default
```
