### ISSUE TITLE
all distributions of Kubeflow 1.1 have incorrect container images

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/manifests#1553]
Currently, this repository (both `master` and `v1.1-branch`) have the incorrect images for some components of kubefow.
As far as I can see, this should affect all stacks at least partially, including: GCP, AWS, Azure, IBM, Vanilla K8S.

Most of these errors have occurred because the stacks have moved to the `base_v3` versions of the components, whereas the maintainers/bot has only updated the `base` spec. But in some cases, clearly no-one is maintaining the YAML for the component.

In terms of fixing this, we obviously need the owners of each section to fix their manifests.

Assuming we fix these issues, and cherry-pick them into the `v1.1-branch`, there will still be an issue, as [kfdef files](https://github.com/kubeflow/manifests/tree/master/kfdef) target the branch directly rather than a tag, so users may not realise that if they rerun `kfctl build ...` they will get different manifests.

Related issues: #1496

## admission-webhook
* Current: `gcr.io/kubeflow-images-public/admission-webhook:vmaster-gaf96e4e3`
* Actual: `gcr.io/kubeflow-images-public/admission-webhook:v1.1.0-g3ac3d08b`
* Code: [./admission-webhook/webhook/base/kustomization.yaml#L18](https://github.com/kubeflow/manifests/blob/master/admission-webhook/webhook/base/kustomization.yaml#L18)
* Owners: @Jeffwan

## centraldashboard
* Current: `gcr.io/kubeflow-images-public/centraldashboard:vmaster-gf39279c0`
* Actual: `gcr.io/kubeflow-images-public/centraldashboard:v1.1.0-g35d7484a`
* Code: [./common/centraldashboard/base_v3/kustomization.yaml#L6](https://github.com/kubeflow/manifests/blob/master/common/centraldashboard/base_v3/kustomization.yaml#L6)
* Owners: ???????

## jupyter-web-app
* Current: `gcr.io/kubeflow-images-public/jupyter-web-app:vmaster-gd9be4b9e`
* Actual: `gcr.io/kubeflow-images-public/jupyter-web-app:v1.1.0-gd3377cbd`
* Code: [./jupyter/jupyter-web-app/base_v3/kustomization.yaml#L32](https://github.com/kubeflow/manifests/blob/master/jupyter/jupyter-web-app/base_v3/kustomization.yaml#L32)
* Owners: @Jeffwan, @kimwnasptd

## notebook-controller
* Current: `gcr.io/kubeflow-images-public/notebook-controller:vmaster-gf39279c0`
* Actual: `gcr.io/kubeflow-images-public/notebook-controller:v1.1.0-gd3377cbd`
* Code: [./jupyter/notebook-controller/base_v3/kustomization.yaml#L15](https://github.com/kubeflow/manifests/blob/master/jupyter/notebook-controller/base_v3/kustomization.yaml#L15)
* Owners: @Jeffwan, @kimwnasptd

## kfam
* Current: `gcr.io/kubeflow-images-public/kfam:vmaster-gf3e09203`
* Actual: `gcr.io/kubeflow-images-public/kfam:v1.1.0-g9f3bfd00`
* Code: [./profiles/base_v3/kustomization.yaml#L9](https://github.com/kubeflow/manifests/blob/master/profiles/base_v3/kustomization.yaml#L9)
* Owners: @Jeffwan

## profile-controller
* Current: `gcr.io/kubeflow-images-public/profile-controller:vmaster-g34aa47c2`
* Actual: `gcr.io/kubeflow-images-public/profile-controller:v1.1.0-ga49f658f`
* Code: [./profiles/base_v3/kustomization.yaml#L12](https://github.com/kubeflow/manifests/blob/master/profiles/base_v3/kustomization.yaml#L12)
* Owners: @Jeffwan

## pytorch-operator
* Current: `gcr.io/kubeflow-images-public/pytorch-operator:vmaster-gd596e904`
* Actual: `gcr.io/kubeflow-images-public/pytorch-operator:v1.1.0-gd596e904`
* Code: [./pytorch-job/pytorch-operator/base/kustomization.yaml#L15](https://github.com/kubeflow/manifests/blob/master/pytorch-job/pytorch-operator/base/kustomization.yaml#L15)
* Owners: @andreyvelich @gaocegege @Jeffwan @johnugeorge

## tf_operator
* Current: `gcr.io/kubeflow-images-public/tf_operator:vmaster-ga2ae7bff`
* Actual: `gcr.io/kubeflow-images-public/tf_operator:v1.1.0-g92389064`
* Code: [./tf-training/tf-job-operator/base/kustomization.yaml#L15](https://github.com/kubeflow/manifests/blob/master/tf-training/tf-job-operator/base/kustomization.yaml#L15)
* Owners: @andreyvelich @gaocegege @Jeffwan @johnugeorge

**Comment by thesuperzapper** [comment]
@jlewi you might want to be across this

**Comment by jlewi** [comment]
@thesuperzapper I would suggest breaking this issue upto into specific issues for each each application and assigning it to the application owners. Application owners are responsible for ensuring their manifests are shipping the right docker image release.

**Comment by jlewi** [comment]
I spot checked the date of the commits of two of the images:
(TFJob) Jun 22 - https://github.com/kubeflow/tf-operator/tree/a2ae7bff612bf26d0b05a54ddcfc6a400a5c8e89 
(Jupyter Web app) Feb 6 - https://github.com/kubeflow/kubeflow/tree/d9be4b9e
(Notebook controller)  Feb 25 - https://github.com/kubeflow/kubeflow/tree/f39279c0

The apps cd pipeline looks like it has entries to update the base_v3 entry for most manifests
https://github.com/kubeflow/testing/blob/d4394eaff73af5645d156412f1de374aba31bf33/apps-cd/applications.yaml#L85

Likewise there are auto opened the PRs to update the manifests
https://github.com/kubeflow/manifests/pull/1479

So it looks to me like application owners didn't review the PRs and get them merged and they missed the release train.

**Comment by jlewi** [comment]
@thesuperzapper Can you and the other proposed notebook lead fix this for notebooks?

**Comment by thesuperzapper** [comment]
For anyone who comes across this issue and needs a fix, add this to your `images` section inside `./kustomize/kubeflow-apps/kustomization.yaml` which was generated by `kfctl build`:

```yaml
images:
  - name: gcr.io/kubeflow-images-public/admission-webhook
    newName: gcr.io/kubeflow-images-public/admission-webhook
    newTag: v1.1.0-g3ac3d08b
  - name: gcr.io/kubeflow-images-public/centraldashboard
    newName: gcr.io/kubeflow-images-public/centraldashboard
    newTag: v1.1.0-g35d7484a
  - name: gcr.io/kubeflow-images-public/jupyter-web-app
    newName: gcr.io/kubeflow-images-public/jupyter-web-app
    newTag: v1.1.0-gd3377cbd
  - name: gcr.io/kubeflow-images-public/notebook-controller
    newName: gcr.io/kubeflow-images-public/notebook-controller
    newTag: v1.1.0-gd3377cbd
  - name: gcr.io/kubeflow-images-public/kfam
    newName: gcr.io/kubeflow-images-public/kfam
    newTag: v1.1.0-g9f3bfd00
  - name: gcr.io/kubeflow-images-public/profile-controller
    newName: gcr.io/kubeflow-images-public/profile-controller
    newTag: v1.1.0-ga49f658f
  - name: gcr.io/kubeflow-images-public/pytorch-operator
    newName: gcr.io/kubeflow-images-public/pytorch-operator
    newTag: v1.1.0-gd596e904
  - name: gcr.io/kubeflow-images-public/tf_operator
    newName: gcr.io/kubeflow-images-public/tf_operator
    newTag: v1.1.0-g92389064
```
