### ISSUE TITLE
Azure installation error: TLS match must have at least one SNI host

### ISSUE THREAD

**Issue by uipo78** [kubeflow/manifests#1667]
I'm attempting to deploy kubeflow on an AKS v1.18.8 cluster, but encountered the following error: 

```
WARN[0055] Encountered error applying application istio:  (kubeflow.error): Code 500 with message: Apply.Run : [error when applying patch:
{"spec":{"tls":[{"match":[{"port":443,"sni_hosts":["www.googleapis.com"]}],"route":[{"destination":{"host":"www.googleapis.com","port":{"number":443}},"weight":100}]}]}}
to:
Resource: "networking.istio.io/v1alpha3, Resource=virtualservices", GroupVersionKind: "networking.istio.io/v1alpha3, Kind=VirtualService"
Name: "google-api-vs", Namespace: "kubeflow"
Object: &{map["apiVersion":"networking.istio.io/v1alpha3" "kind":"VirtualService" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"kind\":\"VirtualService\",\"metadata\":{\"annotations\":{},\"name\":\"google-api-vs\",\"namespace\":\"kubeflow\"},\"spec\":{\"hosts\":[\"www.googleapis.com\"],\"tls\":[{\"match\":[{\"port\":443,\"sni_hosts\":[\"www.googleapis.com\"]}],\"route\":[{\"destination\":{\"host\":\"www.googleapis.com\",\"port\":{\"number\":443}},\"weight\":100}]}]}}\n"] "creationTimestamp":"2020-11-16T23:31:52Z" "generation":'\x01' "managedFields":[map["apiVersion":"networking.istio.io/v1alpha3" "fieldsType":"FieldsV1" "fieldsV1":map["f:metadata":map["f:annotations":map[".":map[] "f:kubectl.kubernetes.io/last-applied-configuration":map[]]] "f:spec":map[".":map[] "f:hosts":map[] "f:tls":map[]]] "manager":"kfctl" "operation":"Update" "time":"2020-11-16T23:31:52Z"]] "name":"google-api-vs" "namespace":"kubeflow" "resourceVersion":"7078778" "selfLink":"/apis/networking.istio.io/v1alpha3/namespaces/kubeflow/virtualservices/google-api-vs" "uid":"2a2b4c93-f128-414a-a383-9b031540fd98"] "spec":map["hosts":["www.googleapis.com"] "tls":[map["match":[map["port":'\u01bb']] "route":[map["destination":map["host":"www.googleapis.com" "port":map["number":'\u01bb']] "weight":'d']]]]]]}
for: "/tmp/kout247395750": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: TLS match must have at least one SNI host, error when applying patch:
{"spec":{"tls":[{"match":[{"port":443,"sni_hosts":["storage.googleapis.com"]}],"route":[{"destination":{"host":"storage.googleapis.com","port":{"number":443}},"weight":100}]}]}}
to:
Resource: "networking.istio.io/v1alpha3, Resource=virtualservices", GroupVersionKind: "networking.istio.io/v1alpha3, Kind=VirtualService"
Name: "google-storage-api-vs", Namespace: "kubeflow"
Object: &{map["apiVersion":"networking.istio.io/v1alpha3" "kind":"VirtualService" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"kind\":\"VirtualService\",\"metadata\":{\"annotations\":{},\"name\":\"google-storage-api-vs\",\"namespace\":\"kubeflow\"},\"spec\":{\"hosts\":[\"storage.googleapis.com\"],\"tls\":[{\"match\":[{\"port\":443,\"sni_hosts\":[\"storage.googleapis.com\"]}],\"route\":[{\"destination\":{\"host\":\"storage.googleapis.com\",\"port\":{\"number\":443}},\"weight\":100}]}]}}\n"] "creationTimestamp":"2020-11-16T23:31:52Z" "generation":'\x01' "managedFields":[map["apiVersion":"networking.istio.io/v1alpha3" "fieldsType":"FieldsV1" "fieldsV1":map["f:metadata":map["f:annotations":map[".":map[] "f:kubectl.kubernetes.io/last-applied-configuration":map[]]] "f:spec":map[".":map[] "f:hosts":map[] "f:tls":map[]]] "manager":"kfctl" "operation":"Update" "time":"2020-11-16T23:31:52Z"]] "name":"google-storage-api-vs" "namespace":"kubeflow" "resourceVersion":"7078779" "selfLink":"/apis/networking.istio.io/v1alpha3/namespaces/kubeflow/virtualservices/google-storage-api-vs" "uid":"096e5753-267d-4509-953e-a6da22c515df"] "spec":map["hosts":["storage.googleapis.com"] "tls":[map["match":[map["port":'\u01bb']] "route":[map["destination":map["host":"storage.googleapis.com" "port":map["number":'\u01bb']] "weight":'d']]]]]]}
for: "/tmp/kout247395750": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: TLS match must have at least one SNI host]  filename="kustomize/kustomize.go:266"
```

This is the KfDef file that I `kfctl apply -f`'ed:

```yaml
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  namespace: kubeflow
spec:
  applications:  
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: namespaces/base
    name: namespaces
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: application/v3
    name: application
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/azure/application/istio-1-3-1-stack
    name: istio-stack
  - kustomizeConfig: 
      repoRef:
        name: manifests
        path: stacks/kubernetes/application/cluster-local-gateway-1-3-1
    name: cluster-local-gateway
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/azure/application/istio
    name: istio 
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: metacontroller/base
    name: metacontroller
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/azure/application/oidc-authservice
    name: oidc-authservice
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/azure
    name: kubeflow-apps
  repos:
  - name: manifests
    uri: https://github.com/kubeflow/manifests/archive/v1.2-branch.tar.gz    
  version: v1.2-branch
```

Note that I removed the cert-manager components since it'd blow away the cluster's pre-existing cert-manager instance.

Not sure where I should post this issue (here or in the main `kubeflow` repo), so let me know if I should move it elsewhere. Thanks!
