### ISSUE TITLE
How to patch MetalLB with Kustomize?

### ISSUE THREAD

**Issue by tomalbrecht** [kubeflow/manifests#1730]
I am following [this kubeflow guide](https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/#expose-kubeflow) and try to translate it into kustomize scripts. Most steps seem easy to translate, but I do not know how to patch `ipAddresses:` into `istio-ingressgateway-certs` with kustomize. Can anyone help me with this (I am quite new to kustomize).

The problem is, that this IP-Adress is only set, after metallb was deployed. How would I set this field dynamically when deploying?

My Setup:
```yaml
#kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubernetes-dashboard
resources:
# https://raw.githubusercontent.com/google/metallb/v0.8.1/manifests/metallb.yaml
- github.com/metallb/metallb//manifests?ref=v0.8.1
- config-map.yaml
- gateway-certificate.yaml
patchesStrategicMerge:
# Secure with HTTPS
- gateway-service-patch.yaml
# Patch Service Type
- gateway-service-patch2.yaml
```

```yaml
#gateway-certificate.yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: istio-ingressgateway-certs
  namespace: istio-system
spec:
  commonName: istio-ingressgateway.istio-system.svc
  # Use ipAddresses if your LoadBalancer issues an IP
  ipAddresses:
  - $LOADBALANCER_IP
  # Use dnsNames if your LoadBalancer issues a hostname (eg on AWS)
  dnsNames:
  - $HOSTNAME
  isCA: true
  issuerRef:
    kind: ClusterIssuer
    name: kubeflow-self-signing-issuer
  secretName: istio-ingressgateway-certs
```

I asked the same question within the [kustomize repository](https://github.com/kubernetes-sigs/kustomize/issues/3511). Not sure where it belongs to.
