### ISSUE TITLE
Change AWS ALB security group inbound rules 

### ISSUE THREAD

**Issue by hossein-rasi** [kubeflow/manifests#1731]
Hello guys.

I installed the kubeflow in AWS EKS using AWS Cognito version of the installment and I have access to the kubeflow page using a custom domain. The problem is, kfctl by default is creating a security group that is used for the istio-ingress load balancer and the inbound rule is set to accept traffic from [0.0.0.0/0] which means it is open everywhere.
My question is, how can I modify this security group based on my requirement? Is there any way to do that during deployment time? 

I also need to add that the manual changes after infrastructure installment to that security group can not happen as it automatically rolling back to the default setting.

**Comment by kim-sardine** [comment]
Modify `Ingress: istio-ingress`

you can add `inbound-cidrs` or `security-groups` annotations (you can check it [here](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v1.1/guide/ingress/annotation/#access-control))

```yaml
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: istio-ingress
  namespace: istio-system
  labels:
    kustomize.component: istio-ingress
  annotations:
    alb.ingress.kubernetes.io/inbound-cidrs: '123.123.123.123/32'  # <-- Add your own inbound IP here
    alb.ingress.kubernetes.io/security-groups: sg-xxxx # <-- Or you can specify predefined security group here
```

then your load balancer will soon be updated
