### ISSUE TITLE
As a user i want to create a seldon deployment at the end of a pipeline

### ISSUE THREAD

**Issue by juliusvonkohout** [kubeflow/manifests#1764]
In a multi-user kubeflow installation each user should be able to create seldon AND kfserving deployments inside his namespace.

 for kfserving this is enabled at https://github.com/kubeflow/manifests/blob/f4cca979d3020a04e45db65bc58d7bbfe386ffd6/apps/kfserving/upstream/kfserving-install/base/cluster-role.yaml#L174 AND https://github.com/kubeflow/manifests/blob/f4cca979d3020a04e45db65bc58d7bbfe386ffd6/apps/kfserving/upstream/installs/generic/cluster-role.yaml#L18

I would like to add the following somewhere to fix the problem for seldon too
```
# Kubeflow builds clusterrole kubeflow-edit by aggreagating multiple other clusterroles
# So i add a clusterrole that allows seldon deployments and it will be aggregated because
# of its "aggregate-to-kubeflow-edit" label
# kubeflow-edit is the default role, that is available in each user namespace and used for pipelines. So you can then create seldon deployments from pipelines

cat <<EOF | kubectl apply -f -
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
  name: kubeflow-seldon-edit
rules:
- apiGroups:
    - machinelearning.seldon.io
  verbs:
    - '*'
  resources:
    - 'seldondeployments'
EOF
```

shall i add it here https://github.com/kubeflow/manifests/blob/master/contrib/seldon/seldon-core-operator/base/resources.yaml ?
