### ISSUE TITLE
Enable DEX authz in Sidecar Proxy Instead of Ingress Gateway

### ISSUE THREAD

**Issue by aaron-arellano** [kubeflow/manifests#1834]
Hello Manifests. I am re-opening an issue based on this one from last year: [https://github.com/kubeflow/manifests/issues/1191]. We are still exploring how to configure the EnvoyFilter for DEX authentication to authenticate on kubeflow service sidecars instead of having the filter at the ingress gateway. 

Like the previous issue we tried to re-explore Istio documentation but none of the recommendations work in Kubeflow. 
This is what we currently have that works for ingress gateway:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authn-filter
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.ext_authz
        config:
          http_service:
            server_uri:
              uri: http://authservice.istio-system.svc.cluster.local
              cluster: outbound|8080||authservice.istio-system.svc.cluster.local
              failure_mode_allow: false
              timeout: 10s
            authorization_request:
              allowed_headers:
                patterns:
                - exact: "cookie"
                - exact: "X-Auth-Token"
            authorization_response:
              allowed_upstream_headers:
                patterns:
                - exact: "kubeflow-userid"
          status_on_error:
            code: GatewayTimeout
```

We want to move to something like this for sidecar inbound with sidecars enabled on our KF services but nothing works. I tried the below config with sidecars enabled on KF UI services but get no redirect to our auth service. If I omit the workloadSelector and keep metadata as above I get a 504. Is there any working solution to move this filter out of ingressgateway. I am using Kubeflow v1.1.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authn-filter
  namespace: kubeflow # scope to KF ns instead of entire ingress
spec:
  workloadSelector:
    labels:
      app: centraldashboard #may be changed to other UI services, this is just to test
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND # scope inbound auth redirect to sidecars
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.ext_authz
        config:
          http_service:
            server_uri:
              uri: http://authservice.istio-system.svc.cluster.local
              cluster: outbound|8080||authservice.istio-sytem.svc.cluster.local
              failure_mode_allow: false
              timeout: 10s
            authorization_request:
              allowed_headers:
                patterns:
                - exact: "cookie"
                - exact: "X-Auth-Token"
            authorization_response:
              allowed_upstream_headers:
                patterns:
                - exact: "kubeflow-userid"
          status_on_error:
            code: GatewayTimeout
```
