### ISSUE TITLE
Kubeflow 1.2 oidc-authservice fails to start with self-signed CA cert

### ISSUE THREAD

**Issue by nicksettje** [kubeflow/manifests#1835]
This issue is similar to https://github.com/kubeflow/manifests/issues/1168 but that issue did not resolve the problem of the unknown CA authority.

I am deploying Kubeflow 1.2 on Digital Ocean Kubernetes and trying to enable HTTPS as described in the Kubeflow docs: https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/#secure-with-https

I deploy Kubeflow directly from https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_istio_dex.v1.2.0.yaml via `kfctl apply -f`.

Then I do the following:
-  Update the `Gateway` resource as described in the docs
-  Patch the `istio-ingressgateway` to be of type `LoadBalancer`. This causes Digital Ocean automatically to provision a DO Load Balancer that is connected to my k8s cluster.
-  Update my DNS to have an A record that points at the IP address of the Load Balancer. Let's say that my DNS name is `example.com`.
- Create the self-signed cert-manager Certificate, setting `dnsNames: [example.com]`
- Update the `oidc-authservice-parameters` ConfigMap so that `oidc_provider: "https://example.com"`
- Update the `authservice` Service so that the env var `OIDC_PROVIDER` is set to `https://example.com`
- Restart `authservice` Service

When I check the logs for `authservice`, I see the following error:
```
level=error msg="OIDC provider setup failed, retrying in 10 seconds: Get https://example.com/dex/.well-known/openid-configuration: x509: certificate signed by unknown authority"
```

Based on the similar issue at the top of this issue, I also tried mounting the `ca.crt` secret from `istio-ingressgateway-certs` that was created as part of the cert-manager Certificate. The `spec` for `authservice` looks like:
```
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
      app.kubernetes.io/component: oidc-authservice
      app.kubernetes.io/name: oidc-authservice
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: authservice
        app.kubernetes.io/component: oidc-authservice
        app.kubernetes.io/name: oidc-authservice
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: authservice-pvc
        - name: ca-cert
          secret:
            secretName: istio-ingressgateway-certs
            items:
              - key: ca.crt
                path: b64
            defaultMode: 511
      containers:
        - name: authservice
          image: 'gcr.io/arrikto/kubeflow/oidc-authservice:28c59ef'
          command:
            - /bin/sh
          args:
            - '-c'
            - ls -R /cert && cat /cert/b64 && env && ./oidc-authservice
          ports:
            - name: http-api
              containerPort: 8080
              protocol: TCP
          env:
            - name: USERID_HEADER
              value: kubeflow-userid
            - name: USERID_PREFIX
            - name: USERID_CLAIM
              value: email
            - name: OIDC_PROVIDER
              value: 'https://example.com/dex'
            - name: OIDC_AUTH_URL
              value: /dex/auth
            - name: OIDC_SCOPES
              value: profile email groups
            - name: REDIRECT_URL
              value: /login/oidc
            - name: SKIP_AUTH_URI
              value: /dex
            - name: PORT
              value: '8080'
            - name: CLIENT_ID
              value: kubeflow-oidc-authservice
            - name: CLIENT_SECRET
              value: <HARDCODED SECRET>
            - name: STORE_PATH
              value: /var/lib/authservice/data.db
            - name: CA_BUNDLE
              value: /cert/b64
          resources: {}
          volumeMounts:
            - name: data
              mountPath: /var/lib/authservice
            - name: ca-cert
              readOnly: true
              mountPath: /cert
          readinessProbe:
            httpGet:
              path: /
              port: 8081
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        fsGroup: 111
      schedulerName: default-scheduler
  serviceName: authservice
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
```

where I use `command` and `args` to debug that the cert is mounted and placed correctly. The env var `CA_BUNDLE` is also set as expected. Nevertheless, I see the same error about `unknown certificate authority`.

How should I configure my Kubeflow deployment to use HTTPS?
