### ISSUE TITLE
doc: default account for user email

### ISSUE THREAD

**Issue by hsinhoyeh** [kubeflow/manifests#1870]
Hi guys,

the default account is `user@example.com` as the original user `user` was gone in this commit (https://github.com/kubeflow/manifests/commit/c5cb42f02f8513259ed19e41977b53e838c0d2e5)
```
kubectl describe configmap dex -n auth
...
staticPasswords:
- email: user@example.com
  hash: $2y$12$4K/VkmDd1q1Orb3xAt82zu8gk7Ad6ReFR4LCP9UeYE90NLiN9Df72
  # https://github.com/dexidp/dex/pull/1601/commits
  # FIXME: Use hashFromEnv instead
  username: user
  userID: "15841185641784"

```

however, [README.md](https://github.com/kubeflow/manifests/blob/master/README.md#installation) still use `user`:
```
In both options, we use a default username (user) and password (12341234).
```
