### ISSUE TITLE
reference the upstream manifests in kustomize (rather than duplicate them)

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/manifests#1874]
We dont have to include the actual YAML from upstream repos in `kubeflow/manifests`! Kustomize can directly reference the upstream repo, at a specific version tag.

__For example, referencing `crud-web-apps` in `kubeflow/kubeflow`:__
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/kubeflow/components/crud-web-apps/jupyter/manifests/overlays/istio?ref=v1.3-branch
```

Should save lots of time/effort, and let us reference `master` in the non `1.X-branch`.

**Comment by thesuperzapper** [comment]
@kubeflow/wg-manifests-leads, what are your thoughts?

cc @yanniszark @DavidSpek

**Comment by DavidSpek** [comment]
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/kubeflow/components/centraldashboard/manifests/overlays/istio?ref=8901e3af3b83f599b89562162cdb2854f57082d3 # tag=v1.3.0-rc.1

patchesStrategicMerge:
- centraldashboard-config.yaml

images:
- name: public.ecr.aws/j1r0q0g6/notebooks/central-dashboard
  newName: public.ecr.aws/j1r0q0g6/notebooks/central-dashboard
  newTag: v1.3.0-rc.1
```
