### ISSUE TITLE
"-license-compliance" image for workflow-controller breaks arm64 support for kfp

### ISSUE THREAD

**Issue by iptizer** [kubeflow/manifests#1889]
[This patch](https://github.com/kubeflow/manifests/blob/master/apps/pipeline/upstream/third-party/argo/base/workflow-controller-deployment-patch.yaml#L15) changes the repository from upstream *argoproj/argoexec* to *gcr.io/ml-pipeline/argoexec*. Problem is, that *argoproj/argoexec* supplies *arch=arm64*... gcr doesn't.

So arm support for the "argoexec" doesn't work though it could.

Workaround is the following "reverse" patch:

```yml
- target:
    kind: Deployment
    name: workflow-controller
  patch: |-
    - op: replace 
      path: /spec/template/spec/containers/0/args
      value:
        - --configmap
        - workflow-controller-configmap
        - --executor-image
        - argoproj/argoexec:v2.12.9
```

Maybe other images are also affected.
