### ISSUE TITLE
Unable to configure dex with oidc

### ISSUE THREAD

**Issue by pthalasta** [kubeflow/manifests#1943]
i'm trying to configure dex+oidc with external authN/Z for logging into to kubeflow. However, the authserver gives the following error post authentication to external server

```
400 Bad Request Response: {\"error_description\":\"Client not found\",\"error\":\"invalid_client\"}
```

I added the following to the config map yaml in my dex configs to enable to oidc connector
```
connectors:
      - type: oidc
        id: oidc-connect
        name: <name>
        config:
          issuer: <issuer>
          clientID: <clientID>
          clientSecret: <secret>
```

I made the necessary changes in `parms.env` for oidc-authorizer to provide the details of issuer. However, if i change the CLIENT_ID/CLIENT_SECRET the flow never works though i've modified the OIDC_CLIENT_ID/SECRET in `dex secret_parms.env` . Can some one explain what are the parameters that needs to be changed or point me to a documentation that i can refer to setup the oidc authorizer?
