### ISSUE TITLE
Central Dashboard Deployment not using the centraldashboard-config ConfigMap

### ISSUE THREAD

**Issue by martialblog** [kubeflow/manifests#1945]
Hi, 

could the be an issue? I've notived the Central Dashboard Deployment is not using the `centraldashboard-config `ConfigMap properly. For example the `REGISTRATION_FLOW` parameter is duplicate, when kustomize-ing the Manifests:

If you run the kustomize build: `kustomize build apps/centraldashboard/upstream/overlays/istio`

It will create the ConfigMap `centraldashboard-parameters`

```
apiVersion: v1
data:
  CD_CLUSTER_DOMAIN: cluster.local
  CD_REGISTRATION_FLOW: "false"
  CD_USERID_HEADER: kubeflow-userid
  CD_USERID_PREFIX: ""
kind: ConfigMap
```

and the Deployment `centraldashboard`

```
apiVersion: apps/v1
kind: Deployment
...
    spec:
      containers:
      - env:
        - name: USERID_HEADER
          value: kubeflow-userid
        - name: USERID_PREFIX
          value: ""
        - name: PROFILES_KFAM_SERVICE_HOST
          value: profiles-kfam.kubeflow
        - name: REGISTRATION_FLOW
          value: "false"
```

Shouldn't the Deployment reference the ConfigMap here? Or am I wrong?

EDIT: Used the master Branch for this (d75f0c18)

Cheers
Markus
