### ISSUE TITLE
mpi-operator: flag provided but not defined: -kubectl-delivery-image

### ISSUE THREAD

**Issue by thuzhf** [kubeflow/manifests#2009]
This is the log from pod `mpi-operator-xxx-xxx` after I run `kustomize build apps/mpi-job/upstream/overlays/kubeflow | kubectl apply -f -`
```
flag provided but not defined: -kubectl-delivery-image
Usage of /opt/mpi-operator:
  -add_dir_header
        If true, adds the file directory to the header
  -alsologtostderr
        log to standard error as well as files
  -gang-scheduling string
        Set gang scheduler name if enable gang scheduling.
  -kube-api-burst int
        Maximum burst for throttle. (default 10)
  -kube-api-qps int
        QPS indicates the maximum QPS to the master from this client. (default 5)
  -kubeConfig string
        Path to a kubeConfig. Only required if out-of-cluster.
  -lock-namespace string
        Set locked namespace name while enabling leader election. (default "mpi-operator")
  -log_backtrace_at value
        when logging hits line file:N, emit a stack trace
  -log_dir string
        If non-empty, write log files in this directory
  -log_file string
        If non-empty, use this log file
  -log_file_max_size uint
        Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
  -logtostderr
        log to standard error instead of files (default true)
  -master string
        The url of the Kubernetes API server,
                         will overrides any value in kubeconfig, only required if out-of-cluster.
  -monitoring-port int
        Endpoint port for displaying monitoring metrics. It can be set to "0" to disable the metrics serving.
  -namespace string
        The namespace to monitor mpijobs. If unset, it monitors all namespaces cluster-wide.
                        If set, it only monitors mpijobs in the given namespace.
  -skip_headers
        If true, avoid header prefixes in the log messages
  -skip_log_headers
        If true, avoid headers when opening log files
  -stderrthreshold value
        logs at or above this threshold go to stderr (default 2)
  -threadiness int
        How many threads to process the main logic (default 2)
  -v value
        number for the log level verbosity
  -version
        Show version and quit
  -vmodule value
        comma-separated list of pattern=N settings for file-filtered logging
```

But when I modify `apps/mpi-job/upstream/base/deployment.yaml` to be the following, and re-run kustomize:
``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpi-operator
  template:
    metadata:
      labels:
        app: mpi-operator
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - args:
        - -alsologtostderr
        - --lock-namespace
        - $(lock-namespace)
        # - --kubectl-delivery-image # NOTICE this line
        # - $(kubectl-delivery-image) # NOTICE this line
        image: mpioperator/mpi-operator:latest
        imagePullPolicy: Always
        name: mpi-operator
      serviceAccountName: mpi-operator
```
The `mpi-operator-xxx-xxx` pod's log becomes:
```
I0908 09:28:44.458061       1 server.go:88] Using cluster scoped operator
I0908 09:28:44.458101       1 server.go:94] [API Version: v1 Version: v0.3.0 Git SHA: db6930dcd509b1d97a47bcccd1bcb1da5eaea712 Built: 2021-09-03 16:02:16 Go Version: go1.15.13 Go OS/Arch: linux/amd64]
I0908 09:28:44.458113       1 server.go:97] Server options: &{Kubeconfig: MasterURL: Threadiness:2 MonitoringPort:0 PrintVersion:false GangSchedulingName: Namespace: LockNamespace:kubeflow QPS:5 Burst:10}
W0908 09:28:44.458201       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
E0908 09:28:44.465594       1 server.go:291] the server could not find the requested resource (get mpijobs.kubeflow.org)
I0908 09:28:44.465611       1 server.go:123] CRD doesn't exist. Exiting
```

Is this a bug or what? How can I solve this problem?
