### ISSUE TITLE
istio VirtualService causes 404 of GET on `/pipelineS`

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/manifests#2031]
Currently, if a user goes to the `/pipelineS` subpath of their Kubeflow URL, they will be met with a 404, for example, `http://kubeflow.example.com/pipelineS` _(NOTE: the `"S"` is capitalized for emphasis, but could be any string, including a `"s"`)_. 

This is because our Istio VirtualServices use [`prefix: /pipeline`](https://github.com/kubeflow/manifests/blob/fdf25f49e7ff4f1d8d097865a77f8b3227c816ce/apps/pipeline/upstream/base/installs/multi-user/virtual-service.yaml#L13), which still matches `/pipelinesXXXX`, and therefore sends this traffic to the `Service/ml-pipeline-ui`.

This is a problem because many users often mistype `http://kubeflow.example.com/pipelines` _(NOTE: the `"s"`, which is incorrect)_, and when trying to authorize using a method like described in https://github.com/kubeflow/website/issues/2916, it's not helpful to receive a 404 when the Istio auth was actually successful. 

__We can fix this using a VirtualService with both an `exact` AND `prefix` match__ 
_(NOTE: `match` possiblities are boolean OR)_
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ml-pipeline-ui
spec:
  gateways:
    - kubeflow-gateway
  hosts:
    - '*'
  http:
    - match:
        ## match the exact `/pipeline` URI
        - uri:
            exact: /pipeline

        ## match all URIs under `/pipeline/` (but not `/pipelineX`)
        - uri:
            prefix: /pipeline/

      route:
        - destination:
            host: ml-pipeline-ui.$(kfp-namespace).svc.cluster.local
            port:
              number: 80
```
