### ISSUE TITLE
authorization policy issue trying to curl within same namespace

### ISSUE THREAD

**Issue by Omoong** [kubeflow/manifests#2201]
So im trying to run some kserve tests on kubeflow 1.5.
I get a rbac: access denied when i try to curl the inferenceservice through the knative-local-gateway from a notebook inside the same namespace as the inferenceservice. 
This is an issue because when this happens the transformer inside the inferenceservice gets the same error while communicating with the predictor.
As a temporary solution I found that the current kubeflow has an istio global deny all authorization policy configured and by configuring an allow-all to the namespace you can bypass the global deny all

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-all
  namespace: kubeflow-user-example-com
spec:
 rules:
 - {}
```

while this allows me to run tests and such but this also allows all requests to be accepted to the namespace and which is not what i want.
im testing to figure out which rules needs to be configured to just allow the requests for the inferenceservices but have yet to succeed... 
If you have any ideas or answers to this problem please help!!
Thank you
