### ISSUE TITLE
Insecure Istio configuration in Kubeflow 1.6

### ISSUE THREAD

**Issue by surajkota** [kubeflow/manifests#2285]
istio-ingressgateway service is set to [type LoadBalancer in 1.6 by default](https://github.com/kubeflow/manifests/blob/master/common/istio-1-14/istio-install/base/install.yaml#L3603) which will open a external endpoint to the service without a TLS/SSL certificate if a user has any load balancer controller installed in their cluster. This is unexpected and undocumented change in behaviour for users and is also insecure depending on the defaults the load balancer controller will use. (e.g. on AWS, if you have aws-load-balancer-controller installed, it will open HTTP port as well and hence we would not recommend anyone to install 1.6 from this repository without modifications)

There are a few more customisations documented here which are good security practices and bug fixes but have not been applied in 1.6 - https://github.com/kubeflow/manifests/tree/master/common/istio-1-14#changes-to-the-upstream-manifests-using-kustomize. It is worth considering applying these for 1.6 as well.

[1.6](https://github.com/kubeflow/manifests/blob/master/common/istio-1-14/istio-install/base/kustomization.yaml) vs [1.5](https://github.com/kubeflow/manifests/blob/v1.5-branch/common/istio-1-11/istio-install/base/kustomization.yaml#L5-L15)

**Comment by kimwnasptd** [comment]
Thanks for catching this! We indeed don't want the Service type to be `LoadBalancer` for the reasons you described above. The reason this ended up happening is due to a bug, which I'll get to in a second.

> istio-ingressgateway service is set to [type LoadBalancer in 1.6 by default](https://github.com/kubeflow/manifests/blob/master/common/istio-1-14/istio-install/base/install.yaml#L3603)

Small clarification, this is the case for the default `profile.yaml` that is autogenerated, and as a result in the `install.yaml` that get produced.

https://github.com/kubeflow/manifests/blob/v1.6-branch/common/istio-1-14/istio-install/base/install.yaml#L3603
https://github.com/kubeflow/manifests/blob/v1.5-branch/common/istio-1-11/istio-install/base/install.yaml#L3499

The problem in this case is, as you had also described, the fact that in the new [`kustomization.yaml`](https://github.com/kubeflow/manifests/blob/v1.6-branch/common/istio-1-14/istio-install/base/kustomization.yaml) we have a bug and didn't apply the extra patches we have. We have a patch specifically for using `NodePort`, which we should be applying https://github.com/kubeflow/manifests/blob/v1.6-branch/common/istio-1-14/istio-install/base/patches/service.yaml

We have a PR to fix this bug in 1.6.1 with @dpoulopoulos https://github.com/kubeflow/manifests/pull/2288

**Comment by kimwnasptd** [comment]
We could also extend the small docs to expose this decision as well
https://github.com/kubeflow/manifests/tree/master/common/istio-1-14#changes-to-the-upstream-manifests-using-kustomize

**Comment by juliusvonkohout** [comment]
Why are you using nodeport instead of ClusterIP ?

**Comment by juliusvonkohout** [comment]
The istio nodeport (loadbalancer)instead of a proper CLusterIP also seems dangerous and unnecessary to me https://oteemo.com/think-nodeport-kubernetes/

**Comment by juliusvonkohout** [comment]
I used the following to fix it 

```
patchesStrategicMerge:
# Pentest enahncement: check port 15010 & 8080 in istiod: According to https://istio.io/latest/docs/ops/best-practices/security/#control-plane port 15010 is not that problematic (only resource discovery). Other parts of the documentation also say | 15010 | GRPC | XDS and CA services (Plaintext, only for secure networks) | We have a secure network layer and only XDS is served. Port 8080 is not listed in the service and even if it would be somehow reachable by IP it only "offers read access". Nevertheless we set ENABLE_DEBUG_ON_HTTP=false do disable it entirely.
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: istiod
    namespace: istio-system
  spec:
    template:
      spec:
        containers:
        - name: discovery
          env:
          - name: ENABLE_DEBUG_ON_HTTP
            value: 'false'
# https://github.com/kubeflow/manifests/issues/2285
- |-
  apiVersion: v1
  kind: Service
  metadata:
    name: istio-ingressgateway
    namespace: istio-system
  spec:
    type: ClusterIP
```
