### ISSUE TITLE
Seldon: Cant follow the example

### ISSUE THREAD

**Issue by GigliOneiric** [kubeflow/manifests#2302]
I followed the example at https://www.kubeflow.org/docs/external-add-ons/serving/seldon/

Steps done:
1. kubectl create namespace seldon
2. kubectl label namespace seldon serving.kubeflow.org/inferenceservice=enabled
3. Created a language wrapper

```
class Transformer(object):
    def __init__(self):
        pass

    def predict(self, X, feature_names):
        return X
```

`s2i build . seldonio/seldon-core-s2i-python37:1.2.3 seldon-sentiment:0.1 --env MODEL_NAME=Transformer --env  API_TYPE=REST --env  SERVICE_TYPE=MODEL --env  PERSISTENCE=0`

4. Pushed it to docker
```
docker run -d -p 5000:5000 --restart=always --name registry registry:2
docker tag seldon-sentiment:0.1  localhost:5000/seldon-sentiment:0.1 
docker push localhost:5000/seldon-sentiment:0.1  
```
4. Added a SeldonDeployment

```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: seldon-sentiment
  namespace: seldon
spec:
  annotations:
    project_name: NLP Pipeline
    deployment_version: v1
  name: seldon-sentiment
  predictors:
    - componentSpecs:
        - spec:
            containers:
              - image: 'localhost:5000/seldon-sentiment:0.1'
                imagePullPolicy: IfNotPresent
                name: sentiment
                resources:
                  requests:
                    memory: 1Mi
            terminationGracePeriodSeconds: 20
      graph:
        children: []
        endpoint:
          type: REST
        name: sentiment
        type: MODEL
      name: sentiment
      replicas: 1
      annotations:
        predictor_version: v1
```
5. Verified the SeldonDeployment
`kubectl get sdep -n kubeflow-user-example-com seldon-sentiment -o json | jq .status `

```
{
  "address": {
    "url": "http://seldon-sentiment-sentiment.kubeflow-user-example-com.svc.cluster.local:8000/api/v1.0/predictions"
  },
  "deploymentStatus": {
    "seldon-sentiment-sentiment-0-sentiment": {
      "availableReplicas": 1,
      "replicas": 1
    }
  },
  "replicas": 1,
  "serviceStatus": {
    "seldon-sentiment-sentiment": {
      "grpcEndpoint": "seldon-sentiment-sentiment.kubeflow-user-example-com:5001",
      "httpEndpoint": "seldon-sentiment-sentiment.kubeflow-user-example-com:8000",
      "svcName": "seldon-sentiment-sentiment"
    },
    "seldon-sentiment-sentiment-sentiment": {
      "grpcEndpoint": "seldon-sentiment-sentiment-sentiment.kubeflow-user-example-com:9500",
      "httpEndpoint": "seldon-sentiment-sentiment-sentiment.kubeflow-user-example-com:9000",
      "svcName": "seldon-sentiment-sentiment-sentiment"
    }
  },
  "state": "Available"
}
```

6. Port forward to the Istio gateway:
`kubectl port-forward $(kubectl get pods -l istio=ingressgateway -n istio-system -o jsonpath='{.items[0].metadata.name}') -n istio-system 8004:80`

7. Send a prediction request:

`curl -s -d '{"data": {"ndarray":[[1.0, 2.0, 5.0]]}}'    -X POST http://localhost:8004/seldon/seldon/seldon-sentiment-sentiment-0-sentiment/api/v1.0/predictions    -H "Content-Type: application/json" -v`

Output:

```
*   Trying ::1:8004...
* TCP_NODELAY set
* Connected to localhost (::1) port 8004 (#0)
> POST /seldon/seldon/seldon-sentiment-sentiment-0-sentiment/api/v1.0/predictions HTTP/1.1
> Host: localhost:8004
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 39
>
* upload completely sent off: 39 out of 39 bytes
* Recv failure: Connection reset by peer
* Closing connection 0
```
