### ISSUE TITLE
Is it possible to have dex server with keycloak for user administration?

### ISSUE THREAD

**Issue by juangon** [kubeflow/manifests#2379]
Hi! I need to dynamically (and programatically) create profiles for Kubeflow. As stated in documentation, some Custom Resource and configmap edition is needed. I am fine with Custom Resource creation but I think that editing the same configmap for passwords can lead to concurrency problems.

I've read in some opened issue that it's possible to integrate dex server with keycloak, but I coudn't find any documentation about that.

Can someone point me to some documentation or steps in order to achieve it?

Thanks very much!

**Comment by juangon** [comment]
Isn't possible then?

**Comment by axel7083** [comment]
> Dex is an identity service that uses [OpenID Connect ](https://openid.net/connect/)to drive authentication for other apps.[^1]

> Keycloak is an open source identity and access management solution. Keycloak can also authenticate users with existing OpenID Connect or SAML 2.0 Identity Providers.[^2]

You can see they are kinda doing the same thing, but keycloak provide a lot more tools, and options than dex.
Your best choice would probably to replace Dex with Keycloak in your cluster.

## Replacing Dex with Keycloak

Here are some configuration example to replace Dex with Keycloak
**This is not made for production**

### Kubernetes yaml files

We deploy in the `auth` namespace a keycloak deployement, service, and istio virtual-service.

<details>
  <summary>Keycloak deployment</summary>

  ```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:21.0.1
          args: ["start-dev"]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KC_PROXY
              value: edge
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
  ```
  
</details>


<details>
  <summary>Keycloak service</summary>

  ```yaml
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: auth
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  ```
  
</details>

<details>
  <summary>Keycloak istio virtual service</summary>

This is not a very good solution since it does not allow keycloak to loads its resources. But this will do the job for the poc.
  ```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: keycloak
  namespace: auth
spec:
  gateways:
    - kubeflow/kubeflow-gateway
  hosts:
    - '*'
  http:
    - match:
        - uri:
            prefix: /realms/
      route:
        - destination:
            host: keycloak.auth.svc.cluster.local
            port:
              number: 8080

  ```
 
</details>


### Keycloak configuration

In the admin dashboard (you can do port-forward of the keycloak pod).
First create a client, and allows `Client authentication` capability to this client.
Copy the CLIENT_ID and CLIENT_SECRET form the created client.

### oidc-authservice configuration

We need to change the [oidc-authservice](https://github.com/arrikto/oidc-authservice) to use keycloak instead of dex.

First change the secret called `oidc-authservice-client` in namespace `istio-system` with the CLIENT_ID and CLIENT_SECRET created with Keycloak.

Then change in  `oidc-authservice-parameters` configmap in the `istio-system` namespace the following parameters:
- OIDC_AUTH_URL: /realms/master/protocol/openid-connect/auth
- OIDC_PROVIDER: <frontend-url>/realms/master
- SKIP_AUTH_URLS: /realms
- OIDC_SCOPES: profile email 

> The OIDC_PROVIDER cannot be `http://keycloak.auth.svc.cluster.local:8080/realms/master` because the oidc-authservice will use this value to compare with the access_token provider by keycloak, which is going to have as an issuer ("iss" claim) your public address.

> The OIDC_SCOPES must not have "groups" keycloak does not recognize it (need further investigation).

### Testing

Restart the `authservice` statefulset in the `istio-system` namespace.
If something went wrong (black screen, or anything) you can `kubectl logs` in keycloak or `authservice` to check the error, and fix it.

> If your keycloak is using https with a private certificate you need to add the CA_BUNDLE in the authservice, see [oidc-authservice/options](https://github.com/arrikto/oidc-authservice#options).

[^1]: See dex documentation https://dexidp.io/
[^2]: See Keycloak website https://www.keycloak.org/
