### ISSUE TITLE
Kubeflow manifests and kustomize 5

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/manifests#2388]
Kustomize 5 has just been released, with the fix we wanted for ordering https://github.com/kubernetes-sigs/kustomize/issues/3794 https://github.com/kubeflow/manifests/issues/1797.

Will use this issue to expose the current status of installing the Kubeflow manifests with Kustomize 5.

/cc @DomFleischmann @annajung @juliusvonkohout

**Comment by kimwnasptd** [comment]
The situation with Kustomize 5 is that:
1. The manifests can be built, and we can avoid the ordering issue with the fix from https://github.com/kubernetes-sigs/kustomize/issues/3794
2. We can't use the same `kustomization.yaml` for both kustomize 5 and earlier versions, since the [`sortOptions`](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/sortoptions/) field is supported only by Kustomize 5
3. Because of a regression in Kustomize 5 we'll need to slightly adjust some of our commands to work around it https://github.com/kubernetes-sigs/kustomize/issues/5039
4. While the warnings we see are not blockers, for now, we'll need to some manifests work to mitigate them

I'll expose more technical details in the following messages, but I propose that we do the switch and just go with Kustomize 5

**Comment by kimwnasptd** [comment]
Specifically, if we try to build the [`example`](https://github.com/kubeflow/manifests/blob/master/example/kustomization.yaml) we'll get the following warnings (multiple times):
```
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesJson6902' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
```

We could try to do `kustomize edit fix`, but there's a good chance we'll need to do manual changes as well

**Comment by kimwnasptd** [comment]
Next up, if we'd try to apply these manifests we'll see that the generated manifests look like this:
```
2023/02/22 15:47:37 well-defined vars that were never replaced: kfp-app-name,kfp-app-version
apiVersion: v1
kind: Namespace
metadata:
  name: auth
...
```
The problem here is that the line `2023/02/22 15:47:37 well-defined vars that were never replaced: kfp-app-name,kfp-app-version` should have been printed in stderr and not stdout. This is a regression in kustomize 5 https://github.com/kubernetes-sigs/kustomize/issues/5039.

To get around this we can just parse the output and remove such lines with something like `awk '!/well-defined/'`. So the one-liner would now become:
```
 while ! kustomize-5 build example | awk '!/well-defined/' | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done
```

**Comment by kimwnasptd** [comment]
Lastly, in order to solve the initial issue we had with ordering we'll need to use the [`sortOptions`](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/sortoptions/) to modify the ordering. Specifically we'll need this section:
```yaml
sortOptions:
  order: legacy
  legacySortOptions:
    orderFirst:
    - Namespace
    - ResourceQuota
    - StorageClass
    - CustomResourceDefinition
    - MutatingWebhookConfiguration
    - ServiceAccount
    - PodSecurityPolicy
    - Role
    - ClusterRole
    - RoleBinding
    - ClusterRoleBinding
    - ConfigMap
    - Secret
    - Endpoints
    - Service
    - LimitRange
    - PriorityClass
    - PersistentVolume
    - PersistentVolumeClaim
    - Deployment
    - StatefulSet
    - CronJob
    - PodDisruptionBudget
    orderLast:
    - ValidatingWebhookConfiguration
```

Pay close attention to the `MutatingWebhookConfiguration` part. This list is copy-paste from the Kustomize 3.2 code
https://github.com/kubernetes-sigs/kustomize/blob/v3.2.0/pkg/gvk/gvk.go#L82-L106, which is working as expected. A note here that I'm not 100 sure if we need to also move the `ValidatingWebhookConfiguration` higher in the list, but I'll leave this as is for now.

In later versions of kustomize this order was changed, and is what produced the ordering issue described in https://github.com/kubeflow/manifests/issues/1797
https://github.com/kubernetes-sigs/kustomize/blob/kustomize/v4.3.0/kyaml/resid/gvk.go#L136-L163

The only issue with the above though is that users can't use it with earlier versions of Kustomize, since only Kustomize 5 can recognize the `sortOptions` property.
