### ISSUE TITLE
kf1.7.0 Logout button not working with oidc sso

### ISSUE THREAD

**Issue by subasathees** [kubeflow/manifests#2475]
Logout button not working with oidc config, however when I enter the full logout url page gets logout successfully  and active session is getting terminated.
URL: https://<FQDN>/logout --> working when enter manually.
K8s: v1.23.5
kubeflow: v1.7.0
kubeflow migrated from v1.3.1 to v1.7.0

```
# cat common/oidc-authservice/base/params.env
OIDC_PROVIDER=https://<domain>
OIDC_AUTH_URL=https://<domain>/as/authorization.oauth2
OIDC_SCOPES=profile email
REDIRECT_URL=https://<domain>/login/oidc
AUTHSERVICE_URL_PREFIX=/authservice/
SKIP_AUTH_URI=/dex
USERID_HEADER=kubeflow-userid
USERID_PREFIX=
USERID_CLAIM=email
PORT="8080"
STORE_PATH=/var/lib/authservice/data.db
STATIC_DESTINATION_URL=https://<domain>/idp/startSLO.ping
```
Logout button **error** on browser network trace:

![image](https://github.com/kubeflow/manifests/assets/74454989/56222fb6-8dfc-435f-aa38-61924e80beb7)

**Comment by subasathees** [comment]
**Issue is Resolved **

Here is the fix for the same, This happens due to URL_PREFIX and old image.
AUTHSERVICE_URL_PREFIX=/authservice/

**All below followed to fix the issue:**
1. Updated default image to New image i.e **gcr.io/arrikto/oidc-authservice:0c4ea9a**
2. Added below empty values in , as in my env we are not having groups scope defined in AD SSO level.

File: common/oidc-authservice/base/params.env  (Append below )
```
GROUPS_HEADER=
GROUPS_CLAIM=
```
4. Added logout proxy redirection, so that logout button works.

File: authservice-logout.yaml
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: authservice-logout
  namespace: istio-system
spec:
  gateways:
    - kubeflow/kubeflow-gateway
  hosts:
    - '*'
  http:
    - match:
        - uri:
            prefix: /logout
      rewrite:
        uri: /authservice/logout
      route:
        - destination:
            host: authservice.istio-system.svc.cluster.local
            port:
              number: 8080
``` 
```
kubectl apply -f authservice-logout.yaml
```
It's Working Now. :100:
