### ISSUE TITLE
net-istio-webhook pod CrashLoopBackOff

### ISSUE THREAD

**Issue by dominickcjh** [kubeflow/manifests#2523]
# Version
Kubernetes: 1.25.13
Kubeflow: 1.7.0
# Steps To Reproduce
```
kustomize build common/knative/knative-serving/overlays/gateways | kubectl apply -f -
```
# Current Behavior
kubectl get pod -n knative-serving
```
NAME                                     READY   STATUS             RESTARTS       AGE
activator-78c655bdd6-znfm7               2/2     Running            0              3m15s
autoscaler-59868b8b9b-tnllt              2/2     Running            0              3m15s
controller-59f75c99b5-n8kkf              2/2     Running            1 (3m9s ago)   3m15s
domain-mapping-7bf5ddbffc-ttqr5          2/2     Running            2 (3m3s ago)   3m15s
domainmapping-webhook-8686964866-lttdz   2/2     Running            1 (3m7s ago)   3m15s
net-istio-controller-6fc6b6b4dd-6f8hh    2/2     Running            2 (3m ago)     3m15s
net-istio-webhook-65859c56b9-7pd5p       1/2     CrashLoopBackOff   5 (20s ago)    3m15s
webhook-69d7dc78c5-qcv9l                 2/2     Running            1 (3m5s ago)   3m14s
```

kubectl logs -f net-istio-webhook-75f498d9c6-wlrzn -n knative-serving
```
panic: failed to convert the environment variable "WEBHOOK_PORT" : strconv.Atoi: parsing "tcp://10.96.58.164:9090": invalid syntax

goroutine 1 [running]:
knative.dev/pkg/webhook.PortFromEnv(0xc000084730?)
        knative.dev/pkg@v0.0.0-20230418073056-dfad48eaa5d0/webhook/env.go:44 +0x125
main.main()
        knative.dev/net-istio/cmd/webhook/main.go:84 +0x7c
```

**Comment by annajung** [comment]
I am not able to reproduce this issue locally using kinD, could you add more context to the running env and other components being installed

**Comment by dominickcjh** [comment]
> I am not able to reproduce this issue locally using kinD, could you add more context to the running env and other components being installed

Sorry,I'm not good at English.

I solved the problem adding an env variable in common/knative/knative-serving/base/upstream/net-istio.yaml
```
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-istio-webhook
  namespace: knative-serving
...
    spec:
      serviceAccountName: controller
      containers:
        - name: webhook
          image: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook@sha256:bfa1dfea77aff6dfa7959f4822d8e61c4f7933053874cd3f27352323e6ecd985
          resources:
            requests:
              cpu: 20m
              memory: 20Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: WEBHOOK_PORT
              value: 8443
...
```
But I don't know why it doesn't work without this variable.I installed the kubeflow components separately according to the kubeflow official documentation.When I installed knative, the above problem occurred.

And sorry,I've deleted my kubeflow and kubernetes cluster.I can't show you more details.

Thanks.
