### ISSUE TITLE
One owner multiple namespaces

### ISSUE THREAD

**Issue by gfarcas** [kubeflow/manifests#2641]
I have tried creating two profiles with the same user as owner 
The drop down shows me as owner on both
![image](https://github.com/kubeflow/manifests/assets/8426011/cf041581-a52b-4eea-9275-686bd615ac3d)
But when I go to contributing it is different
![image](https://github.com/kubeflow/manifests/assets/8426011/9482096c-0617-4c75-b5c7-aeebd90b94f4)
These are the profile controller logs:
```log
1.7095676167748752e+09	INFO	controllers.Profile	Start to Reconcile.	{"profile": "/upgrade", "namespace": "", "name": "upgrade"}
1.7095676167749074e+09	INFO	controllers.Profile	List of labels to be added to namespace	{"profile": "/upgrade", "labels": {"app.kubernetes.io/part-of":"kubeflow-profile","istio-injection":"enabled","katib.kubeflow.org/metrics-collector-injection":"enabled","pipelines.kubeflow.org/enabled":"true","serving.kubeflow.org/inferenceservice":"enabled"}}
1.709567616774934e+09	INFO	controllers.Profile	List of labels to be added to found namespace	{"profile": "/upgrade", "labels": {"app.kubernetes.io/part-of":"kubeflow-profile","istio-injection":"enabled","katib.kubeflow.org/metrics-collector-injection":"enabled","pipelines.kubeflow.org/enabled":"true","serving.kubeflow.org/inferenceservice":"enabled"}}
1.7095676167751784e+09	INFO	controllers.Profile	Updating RoleBinding	{"profile": "upgrade", "namespace": "upgrade", "name": "namespaceAdmin"}
1.7095676168882513e+09	INFO	controllers.Profile	Start to Reconcile.	{"profile": "/bi-ds", "namespace": "", "name": "bi-ds"}
1.709567616888275e+09	INFO	controllers.Profile	List of labels to be added to namespace	{"profile": "/bi-ds", "labels": {"app.kubernetes.io/part-of":"kubeflow-profile","istio-injection":"enabled","katib.kubeflow.org/metrics-collector-injection":"enabled","pipelines.kubeflow.org/enabled":"true","serving.kubeflow.org/inferenceservice":"enabled"}}
1.7095676168882942e+09	INFO	controllers.Profile	List of labels to be added to found namespace	{"profile": "/bi-ds", "labels": {"app.kubernetes.io/part-of":"kubeflow-profile","istio-injection":"enabled","katib.kubeflow.org/metrics-collector-injection":"enabled","pipelines.kubeflow.org/enabled":"true","serving.kubeflow.org/inferenceservice":"enabled"}}
1.7095676168884087e+09	INFO	controllers.Profile	Updating RoleBinding	{"profile": "bi-ds", "namespace": "bi-ds", "name": "namespaceAdmin"}
```

Version: 1.8.0

**Comment by thesuperzapper** [comment]
Can you share the `Profile` CRD YAML for each profile?

**Comment by gfarcas** [comment]
Sure!
Here they are:
```yaml
#first profile
spec:
  owner:
    kind: User
    name: gfarcas@company.com
  resourceQuotaSpec:
    hard:
      cpu: '32'
      memory: 256Gi

#second profile
spec:
  owner:
    kind: User
    name: gfarcas@company.com
  resourceQuotaSpec:
    hard:
      cpu: '32'
      memory: 256Gi
```
