### ISSUE TITLE
Kubeflow roles do not have the ability to manage ray.io resources

### ISSUE THREAD

**Issue by alex-treebeard** [kubeflow/manifests#2671]
As Kuberay is included in the contrib directory, it may make sense to given users permissions when installing it with resources like this:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeflow-ray-admin
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-admin: 'true'
rules:
- apiGroups:
  - ray.io
  verbs: ["*"]
  resources: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeflow-ray-editor
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: 'true'
rules:
- apiGroups:
  - ray.io
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  resources: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeflow-ray-viewer
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-view: 'true'
rules:
- apiGroups:
  - ray.io
  verbs: ["get", "list", "watch"]
  resources: ["*"]
---
```

Happy to make a PR if this seems right.
