### ISSUE TITLE
Istio Ambient support

### ISSUE THREAD

**Issue by peterj** [kubeflow/manifests#2676]
Istio Ambient mode is a different deployment model from the “traditional” (sidecar) mode of Istio. The ambient mode (sidecar-less) doesn’t require injecting sidecars into the deployments.

Here are the high-level differences between the two modes:

- The concerns handled by the sidecar proxy in the sidecar Istio are split into two components in Istio ambient: 

  - **Ztunnel** (handles L4 concerns, mTLS, authorization policies without any HTTP)

    - Ztunnel is installed automatically when profile=ambient

  - **Waypoint proxy** (handles L7 concerns, i.e. traffic splitting, matching, header manipulation, etc., more or less everything that gets defined in the VirtualService)

    - Waypoint is **optional** (not installed by default) and it can be deployed per service account (handles all workloads using the same service account) or  per namespace (handles L7 proxying for all workloads in the namespace)  

- Ingress gateway isn’t installed by default anymore when using profile=ambient

  - It might be worth migrating over to Kubernetes Gateway APIs and deploying the Istio ingress gateway like that, as we’ll have to use the Gateway APIs to deploy waypoint proxies anyway

- Kubernetes Gateway API is used for ingress (and waypoint proxy) deployments

- Any L7 VirtualServices or AuthorizationPolicies must have a “targetRef” section that specifies which waypoint proxy handles the L7 configuration

## Waypoint proxies<a id="waypoint-proxies"></a>

Any VirtualService or AuthorizationPolicy that uses HTTP concepts will require a waypoint proxy. Given that there are 3 namespaces (that I identified so far), I’d suggest a per-namespace deployment of a waypoint proxy.

In addition to the waypoint proxy, the resources will have to be updated to use the waypoint proxies: 

| **Component**                | **Namespace** | **Notes** |
| --- | --- | --- |
| dex                          | auth          |           |
| central-dashboard            | kubeflow      |           |
| jupyter-web-app              | kubeflow      |           |
| volumes-web-app              | kubeflow      |           |
| katib-ui                     | kubeflow      |           |
| ml-pipeline-ui               | kubeflow      |           |
| metadata-envoy-service       | kubeflow      |           |
| kfp-tekton                   | kubeflow      |           |
| kubebench-dashboard          | kubeflow      |           |
| profiles-kfam                | kubeflow      |           |
| tensorboards-web-app-service | kubeflow      |           |
| kserve-models-web-app        | kserve        |           |

## Work items

- Migrate to Kubernetes Gateway API

  - Update the YAML (/common/istio\*) for deploying ingress and local ingress to use the Gateway API 

- Move to the latest Istio (Ambient will be beta in the next release (1.22))

  - We can still continue with the sidecar mode here

- Move to Ambient mode

  - Identify components that need waypoint proxy

  - Deploy waypoint proxies 

  - Switch the Istio profile from default → ambient (or have an option of doing one or the other) - since Ambient will still be Beta, we shouldn’t make it a default option

**Comment by ca-scribner** [comment]
What are the components that need to change for this?  Would the profile controller need to create waypoint proxies for each user's namespace?

**Comment by peterj** [comment]
Waypoint proxies are automatically created when the Gateway resource gets created (so is a bit simpler than crafting deployments/services). You can configure it in such a way that there's 1 instance per namespace that handles all L7 traffic for that namespace.

**Comment by juliusvonkohout** [comment]
@peterj one waypoint proxy per dynamic on demand namespace would be a critical change.

**Comment by peterj** [comment]
That's how the ambient is designed to handle L7. So instead of running sidecar next to every workload, you run 1 waypoint (L7) proxy per namespace.

**Comment by ca-scribner** [comment]
Yeah I think the profile controller would be instantiating waypoint proxies for each user namespace.  That shouldn't be so hard though (the profile controller already creates other per-namespace resources)

This probably gets more complicated wrt to the Gateway API though.  Do we need to migrate all VirtualServices and such to the Gateway API too?  I'm not clear on what is interoperable

**Comment by peterj** [comment]
The mixing of resources - VirtualService and Gateway API resources - is not supported in ambient. So, it's either Gateway API + HTTPRoute/TLSroute/TCPRoute **or** no Gateway API. 

Is there an inventory of VirtualServices (and features within) currently used by kubeflow? 

From the Istio docs, the following features are supported in HTTPRoutes (Gateway API):
- matching on paths, headers
- mirroring
- weight-based routing
- timeouts

**Comment by ca-scribner** [comment]
Someone else will have to speak to it, but from what I can tell the features from `VirtualServices` used now are covered by `HTTPRoute`.  I'm less sure about `AuthorizationPolicies` and things like authentication on the gateway - do you know the state of those with ambient istio+gateway apis?

**Comment by peterj** [comment]
The RequestAuthentication and AuthorizationPolicies can be used as-is. The only difference is that you have to use "targetRefs" instead of a selector label to point to the service. Here's an example from the docs:

```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: view-only
  namespace: default
spec:
 # THIS IS DIFFERENT- you're targeting a Gateway, instead of using labels.
  targetRefs:
  - kind: Gateway
    group: gateway.networking.k8s.io
    name: default
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["default", "istio-system"]
    to:
    - operation:
        methods: ["GET"]
 ```
 
 And request auth:
 
 ```yaml
 apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: "jwt-example"
  namespace: foo
spec:
  targetRef:
    kind: Gateway
    group: gateway.networking.k8s.io
    name: httpbin-gateway
  jwtRules:
  - issuer: "testing@secure.istio.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.22/security/tools/jwt/samples/jwks.json"
```

But, of course, it would be great to test these things out beforehand :) Is there a good walkthrough and a collection scenarios one can run through that touch these features? (I am not so familiar with kubeflow, but if someone points me to the scenarios, I could probably test it out with Gateway API)

**Comment by juliusvonkohout** [comment]
In a PR you will just trigger many scenarios automatically, so that is the easiest way to test

**Comment by jbottum** [comment]
this is great work, thanks for moving this forward.

**Comment by ca-scribner** [comment]
ty @peterj this is really helpful clarifications! 

Do you know how the Gateway API works for setting up authentication at the gateway?  I'm thinking of [this `EnvoyFilter`](https://github.com/kubeflow/manifests/blob/08f217c1bfb232ebeb05d12f9aa17d5f848c19bb/common/oidc-client/oidc-authservice/base/envoy-filter.yaml#L4) - does it have an equivalent workflow for the new api?

**Comment by peterj** [comment]
I *think* there might be an easier way to define the ext-authz that doesn't use EnvoyFile -- https://istio.io/latest/docs/tasks/security/authorization/authz-custom/ 

Let me open a separate "issue" on this as this could be a lower-hanging fruit to fix (i.e. get rid of EnvoyFilters :)).

**Comment by peterj** [comment]
Also, to answer the original question - based on the [docs here](https://istio.io/latest/docs/ambient/usage/l7-features/#extension) the `targetRefs` could be used to configure the Envoyfilter (but again, should be tested :))

**Comment by juliusvonkohout** [comment]
oidc-authservice will be eliminated soon :-)

**Comment by kimwnasptd** [comment]
This is an amazing effort @peterj! I'd also like to help on the changes required.

Another important component here though is going to be KServe and Knative, that create a lot of VirtualServices under the hood. Knative specifically sounds very scary since we have no influence over, from the Kubeflow side.

cc @yuzisun

**Comment by peterj** [comment]
The Ingress resource still works with Istio (i.e. Istio implements the ingress class - [ref](https://istio.io/latest/docs/tasks/traffic-management/ingress/kubernetes-ingress/)), but it would make sense to move that over to Kubernetes Gateway API.

**Comment by ca-scribner** [comment]
I haven't tested anything in knative yet, but they have [some discussion](https://github.com/knative-extensions/net-istio/issues/1103) of ambient working

**Comment by ca-scribner** [comment]
Something that concerns me with ambient is that [I can't figure out how to do deny-by-default](https://github.com/istio/istio/discussions/53206).  With sidecar, you can create an `allow-nothing` policy that forces all communication to need an Authorization Policy enabling it.  But with ambient, I don't see a good way to do that.

Does anyone have a solution?  It feels like a pretty big hole so I assume I'm missing something here

**Comment by edwardzjl** [comment]
I'm trying to deploy kubeflow with istio ambient mode but I find that it might be difficult to migrate the ext-auth: https://github.com/istio/istio/issues/51214

**Comment by juliusvonkohout** [comment]
We will try istio-cni first for rootless istio, so please help there as well https://github.com/kubeflow/manifests/pull/2907

**Comment by juliusvonkohout** [comment]
> I'm trying to deploy kubeflow with istio ambient mode but I find that it might be difficult to migrate the ext-auth: [istio/istio#51214](https://github.com/istio/istio/issues/51214)

We will try istio-cni first for rootless istio, so please help there as well https://github.com/kubeflow/manifests/pull/2907

**Comment by terrytangyuan** [comment]
KServe community is working on Gateway API migration. See https://github.com/kserve/kserve/pull/3952

**Comment by juliusvonkohout** [comment]
@terrytangyuan we also want to switch our istio to the gateway API.

**Comment by juliusvonkohout** [comment]
Some thoughts to keep in mind: ambient needs one L7 Proxy per namespace which prevents zero overhead namespaces.
If the namespace is idle, which is probably the case for 76% of the time (8x5=40 hours per week / 7*24) you have zero costs and zero overhead with istio-cni. So it is a tradeoff and if you have many namespaces with many pods (after removing the visualization server and artifact proxy) running 24/7 ambient mesh could be better. So I think we should offer both cni+ambient for the time being.

**Comment by jbronn** [comment]
I've finished installing one of the first instances of Kubeflow 1.9.1 using Istio 1.24 (with CNI) in ambient mode.  Here are some of my lessons:

* In order for external authentication to work with Dex/OAuth2 Proxy the `AuthorizationPolicy` / `RequestAuthentication` resources must be associated with a [*Kubernetes* `Gateway` resource](https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#configuring-a-gateway) that's in the same namespace as the ingress gateway deployment and allows traffic from other namespaces, e.g.:

    ```yaml
    ---
    apiVersion: gateway.networking.k8s.io/v1
    kind: Gateway
    metadata:
      name: istio-ingressgateway
      namespace: istio-system
    spec:
      addresses:
        - type: Hostname
          value: istio-ingressgateway.istio-system.svc.cluster.local
      gatewayClassName: istio
      listeners:
        - allowedRoutes:
            namespaces:
              from: All
          name: http
          port: 80
          protocol: HTTP
    ```

  Setting the `addresses` pointing to the ingress gateway deployment is required for [manual installation](https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#manual-deployment), otherwise Istio will automatically create a `Deployment` and `Service`.  Then you must use replace the `selector` with a `targetRef` to the Kubernetes gateway for the `AuthorizationPolicy` / `RequestAuthentication` to actually apply to all ingress traffic:

    ```yaml
    ---
    apiVersion: security.istio.io/v1
    kind: RequestAuthentication
    metadata:
      name: dex-jwt
      namespace: istio-system
    spec:
      targetRef:
        kind: Gateway
        group: gateway.networking.k8s.io
        name: istio-ingressgateway
    ---
    apiVersion: security.istio.io/v1
    kind: AuthorizationPolicy
    metadata:
      name: m2m-token-issuer
      namespace: istio-system
    spec:
      action: CUSTOM
      provider:
        name: oauth2-proxy
      targetRef:
        kind: Gateway
        group: gateway.networking.k8s.io
        name: istio-ingressgateway
    ```

* Istio waypoint proxies are needed in Kubeflow namespace in order to process L7 authorization policies:

    ```yaml
    apiVersion: gateway.networking.k8s.io/v1
    kind: Gateway
    metadata:
      name: istio-waypoint
      namespace: kubeflow
    spec:
      gatewayClassName: istio-waypoint
      listeners:
        - name: mesh
          port: 15008
    ```

  Services using L7 authorization policies need to be updated to use the waypoint, e.g. for `ml-pipeline`:

    ```yaml
    apiVersion: v1
    kind: Service
    metadata:
      name: ml-pipeline
      namespace: kubeflow
      labels:
        istio.io/use-waypoint: istio-waypoint
        ...
    ```

  And authorization policies to be updated to remove the `selector`, add `targetRef` to applicaple service, and add the principal for the waypoint:

    ```yaml
    apiVersion: security.istio.io/v1
    kind: AuthorizationPolicy
    metadata:
      name: ml-pipeline
      namespace: kubeflow
    spec:
      action: ALLOW
      rules:
        - from:
          - source:
              principals:
                - cluster.local/ns/kubeflow/sa/istio-waypoint
                ...
      targetRef:
        group: core
        kind: Service
        name: ml-pipeline
    ```

* Likewise, for user namespaces it's easier to just add the `istio.io/use-waypoint` to the namespace by customizing the `namespace-labels.yaml` of the profiles controller.  However, I had to patch the [profile controller](https://github.com/kubeflow/kubeflow/blob/master/components/profile-controller/controllers/profile_controller.go#L419-L504) to not sync `ns-owner-access-istio` policies and install manually because I couldn't figure out how to its modules.  In particular, it uses [Istio modules](https://github.com/kubeflow/kubeflow/blob/master/components/profile-controller/go.mod#L20-L21) before the advent of ambient APIs like `targetRef` which is needed to attach authorization policies user namespace waypoints.  Updating the Istio module leads to conflicts with the old version of `controller-runtime` used that were beyond my Go abilities.

* Istio `DestinationRule` resources with `ISTIO_MUTUAL` traffic policies (e.g, like [one for `volumes-web-app`](https://github.com/kubeflow/manifests/blob/master/apps/volumes-web-app/upstream/overlays/istio/destination-rule.yaml)) do not work with ambient mode since L4 traffic is already [encrypted with mTLS between workloads](https://istio.io/latest/docs/ambient/usage/verify-mtls-enabled/) and need to be removed.

* [Knative `PeerAuthentication`](https://github.com/kubeflow/manifests/blob/master/common/knative/knative-serving/base/upstream/net-istio.yaml#L186-L203) cannot be used if Istio is has a global `PeerAuthentication` policy set to `STRICT` until istio/istio#53884 is backported to 1.24.

**Comment by juliusvonkohout** [comment]
@jbronn, du you want to create a PR? We would need to use https://istio.io/latest/docs/ambient/usage/waypoint/#usewaypointnamespace to not have extra waypoint proxies per namespaces, but use a global one in the istio-system namespace.

CC @kimwnasptd and we could also propose this in https://github.com/kubeflow/community/issues/809

**Comment by juliusvonkohout** [comment]
See https://github.com/kubeflow/community/issues/809#issuecomment-2633370759 for the Gsoc idea

**Comment by jbronn** [comment]
@juliusvonkohout It will take me some time to come up with a PR as I'll have to wrap my head around the way the Istio manifests are generated here.  For our use case we wanted to decouple our Istio and Argo Workflows deployments completely from Kubeflow's release cycle and installed them using their official charts using ArgoCD.  We also used ArgoCD to install Kubeflow from these manifests but had to patch in updates and resources for ambient compatibility.  I'd like to upstream these more foundational patches first before trying to put together a monster ambient PR.  In particular, I'd start with a PR addressing #2798 since I had to remove those same [deprecated annotations](https://istio.io/latest/docs/reference/config/annotations/#SidecarInject) to ensure they wouldn't override ambient mode on a per-deployment basis.

I also attempted using a single waypoint proxy along with the [`istio.io/use-waypoint-namespace`](https://istio.io/latest/docs/reference/config/labels/#IoIstioUseWaypointNamespace) label.  However, I ran into the limitation that the [`targetRef` of an `AuthorizationPolicy`](https://istio.io/latest/docs/reference/config/security/authorization-policy/#AuthorizationPolicy-targetRefs) only applies in the *same namespace*.  In other words, the existing policies, like [`ml-pipeline-visualizationserver`](https://github.com/kubeflow/manifests/blob/master/apps/pipeline/upstream/base/installs/multi-user/pipelines-profile-controller/sync.py#L226-L246), would have to be redone entirely rather than just modifying source principals.  Likewise, I wouldn't even know where to start modifying the [`ns-owner-access-istio`](https://github.com/kubeflow/kubeflow/blob/master/components/profile-controller/controllers/profile_controller.go#L506-L556) policy for use with a cross-namespace waypoint.  Thus, I settled with a waypoint proxy in the `kubeflow` namespace and every user namespace.

Speaking of `istio-system`, in my implementation I tried to limit what goes into that control plane namespace.  In particular, I moved `cluster-local-gateway` and `istio-ingress` (renamed from `istio-ingressgateway`) to a dedicated `istio-ingress` namespace because it's [recommended as a security best practice](https://istio.io/latest/docs/setup/additional-setup/gateway/#deploying-a-gateway).  Would this be a change the Kubeflow team would consider?

**Comment by juliusvonkohout** [comment]
> [@juliusvonkohout](https://github.com/juliusvonkohout) It will take me some time to come up with a PR as I'll have to wrap my head around the way the Istio manifests are generated here. For our use case we wanted to decouple our Istio and Argo Workflows deployments completely from Kubeflow's release cycle and installed them using their official charts using ArgoCD. We also used ArgoCD to install Kubeflow from these manifests but had to patch in updates and resources for ambient compatibility. I'd like to upstream these more foundational patches first before trying to put together a monster ambient PR. In particular, I'd start with a PR addressing [#2798](https://github.com/kubeflow/manifests/issues/2798) since I had to remove those same [deprecated annotations](https://istio.io/latest/docs/reference/config/annotations/#SidecarInject) to ensure they wouldn't override ambient mode on a per-deployment basis.
> 
> I also attempted using a single waypoint proxy along with the [`istio.io/use-waypoint-namespace`](https://istio.io/latest/docs/reference/config/labels/#IoIstioUseWaypointNamespace) label. However, I ran into the limitation that the [`targetRef` of an `AuthorizationPolicy`](https://istio.io/latest/docs/reference/config/security/authorization-policy/#AuthorizationPolicy-targetRefs) only applies in the _same namespace_. In other words, the existing policies, like [`ml-pipeline-visualizationserver`](https://github.com/kubeflow/manifests/blob/master/apps/pipeline/upstream/base/installs/multi-user/pipelines-profile-controller/sync.py#L226-L246), would have to be redone entirely rather than just modifying source principals. Likewise, I wouldn't even know where to start modifying the [`ns-owner-access-istio`](https://github.com/kubeflow/kubeflow/blob/master/components/profile-controller/controllers/profile_controller.go#L506-L556) policy for use with a cross-namespace waypoint. Thus, I settled with a waypoint proxy in the `kubeflow` namespace and every user namespace.
> 
> Speaking of `istio-system`, in my implementation I tried to limit what goes into that control plane namespace. In particular, I moved `cluster-local-gateway` and `istio-ingress` (renamed from `istio-ingressgateway`) to a dedicated `istio-ingress` namespace because it's [recommended as a security best practice](https://istio.io/latest/docs/setup/additional-setup/gateway/#deploying-a-gateway). Would this be a change the Kubeflow team would consider?

That sounds very good. Please start with the least invasive changes first. Moving the istio-ingress would come last for example.

**Comment by howardjohn** [comment]
> I also attempted using a single waypoint proxy along with the [`istio.io/use-waypoint-namespace`](https://istio.io/latest/docs/reference/config/labels/#IoIstioUseWaypointNamespace) label. However, I ran into the limitation that the [`targetRef` of an `AuthorizationPolicy`](https://istio.io/latest/docs/reference/config/security/authorization-policy/#AuthorizationPolicy-targetRefs) only applies in the _same namespace_. In other words, the existing policies, like [`ml-pipeline-visualizationserver`](https://github.com/kubeflow/manifests/blob/master/apps/pipeline/upstream/base/installs/multi-user/pipelines-profile-controller/sync.py#L226-L246), would have to be redone entirely rather than just modifying source principals. Likewise, I wouldn't even know where to start modifying the [`ns-owner-access-istio`](https://github.com/kubeflow/kubeflow/blob/master/components/profile-controller/controllers/profile_controller.go#L506-L556) policy for use with a cross-namespace waypoint. Thus, I settled with a waypoint proxy in the `kubeflow` namespace and every user namespace.

I haven't looked too closely into what exact resources kubeflow needs but I think this should not be an issue. TargetRef can attach the Gateway ("everything in the waypoint") or the Service (applied only to a single service).

If I have... 
* waypoint in ns istio-system
* service X attached to that waypoint in ns "app" 
* authorization policy targetRef'ing Service X in ns "app" 

then you should get the expected behavior. 

TargetRef of the entire waypoint would need to be in the same namespace though (else anyone could modify it!) but I don't think that should be needed

**Comment by kimwnasptd** [comment]
Took a more detailed look on @jbronn's nice https://github.com/kubeflow/manifests/issues/2676#issuecomment-2613660423 above. 

In my case I was stuck in connecting the `istio-ingressgateway` with the `oauth2-proxy` via the [AuthorizationPolicy](https://github.com/kubeflow/manifests/blob/4b750ba1106c127668340be13d1fe708fc75c3bd/common/oauth2-proxy/components/istio-external-auth/authorizationpolicy.istio-ingressgateway-oauth2-proxy.yaml) and [RequestAuthentication](https://github.com/kubeflow/manifests/blob/4b750ba1106c127668340be13d1fe708fc75c3bd/common/oauth2-proxy/components/istio-external-auth/requestauthentication.dex-jwt.yaml). For my setup I had done the following:
1. Had an (Istio) `Gateway`, attached to the `istio-ingressgateway` Deployment / Service (default deployed with Kubeflow, since we are still using `VirtualServices`)
2. Followed @jbronn's steps above and
    1. Created also a K8s `Gateway`, backed by the same `istio-ingressgateway` Deployment / Service
    2. Updated the above `AuthorizationPolicy` and `RequestAuthentication` to use `targetRefs`

The result of that was that my requests, passing through the `istio-ingressgateway`, were not being checked by `oauth2-proxy` at all and didn't have any `kubeflow-userid` headers set.

**Comment by kimwnasptd** [comment]
After [chatting](https://istio.slack.com/archives/C041EQL1XMY/p1744133864495059) with @howardjohn I learned that we can't use **both** an (Istio) `Gateway` and also a K8s `Gateway` backed by the same Deployment / Service.

So as long as we have `VirtualServices` (i.e. Knative) we'll need to keep using the (Istio) `Gateway`.

In this case though, the `AuthorizationPolicy` and `RequestAuthentication` would look exactly as they are now, using the `selector` to target `istio-ingressgateway` (instead of `targetRefs`, as proposed above).

The status of the `AuthorizationPolicy` is a bit misleading though:
```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  generation: 3
  name: oauth2-proxy-ingressgateway
  namespace: istio-system

spec:
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
  - to:
    - operation:
        notPaths:
        - /dex/*
        - /dex/**
        - /oauth2/*
    when:
    - key: request.headers[authorization]
      notValues:
      - '*'
  selector:
    matchLabels:
      app: istio-ingressgateway
status:
  conditions:
  - lastTransitionTime: "2025-04-08T17:56:11.561839491Z"
    message: ztunnel does not support the CUSTOM action
    observedGeneration: "1"
    reason: UnsupportedValue
    status: "False"
    type: ZtunnelAccepted
```

While the message accurately describes that ztunnel can't accept this `AuthorizationPolicy`, but the selected workload (istio-ingressgateway) doesn't care in this case and gets configured as expected.
