### ISSUE TITLE
Dex Microsoft connector gives me "Unregistered redirect_uri ("/oauth2/callback")."

### ISSUE THREAD

**Issue by JCoupalK** [kubeflow/manifests#2766]
### Validation Checklist

- [X] Is this a Kubeflow issue?
- [X] Are you posting in the right repository ?
- [X] Did you follow the installation guide https://github.com/kubeflow/manifests?tab=readme-ov-file ?
- [X] Is the issue report properly structured and detailed with version numbers?
- [ ] Is this for Kubeflow development ?
- [ ] Would you like to work on this issue?
- [ ] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

master

### Describe your issue

I configured the Dex config-map.yaml to use the Microsoft connector following those instructions:
https://dexidp.io/docs/connectors/microsoft/

Applied and restarted the deployments.

And when I clicked Login with Microsoft I got this:
![image](https://github.com/kubeflow/kubeflow/assets/108779415/fd5912c1-ccb6-43a2-ad6e-c206ea37a464)

I tried to modify the config but anything I tried seemed to result in this Bad request.

Not sure if that's purely a Dex issue or the way it is in Kubeflow.

I expected to be able to login with my Microsoft Azure AD account and access the dashboard.

**Anything else you would like to add:**
My current (censored) config-maps.yaml at ./manifests/common/dex/base/config-map.yaml
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
data:
  config.yaml: |
    issuer: http://dex.auth.svc.cluster.local:5556/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true
    staticClients:
    # https://github.com/dexidp/dex/pull/1664
    - idEnv: OIDC_CLIENT_ID
      redirectURIs: ["/authservice/oidc/callback"]
      name: 'Dex Login Application'
      secretEnv: OIDC_CLIENT_SECRET
    connectors:
      - type: microsoft
        id: microsoft
        name: Microsoft
        config:
          clientID: client-id-here
          clientSecret: secret-here
          redirectURI: https://external.domain.com/dex/callback
          tenant: organizations
          emailToLowercase: true
```

**Environment:**

- Kubeflow version: 1.8.0
- Kubernetes platform: K3S
- Kubernetes version: 1.26.15
- OS: Ubuntu 22.04 LTS
- The istio gateway is also behind an external nginx reverse proxy

### Steps to reproduce the issue

I configured the Dex config-map.yaml to use the Microsoft connector following those instructions:
https://dexidp.io/docs/connectors/microsoft/

Applied and restarted the deployments.

And when I clicked Login with Microsoft I got this:
![image](https://github.com/kubeflow/kubeflow/assets/108779415/fd5912c1-ccb6-43a2-ad6e-c206ea37a464)

### Put here any screenshots or videos (optional)

![image](https://github.com/kubeflow/kubeflow/assets/108779415/fd5912c1-ccb6-43a2-ad6e-c206ea37a464)

My (censored) Azure app:
![image](https://github.com/kubeflow/kubeflow/assets/108779415/9deb7ce7-4b29-45ac-8bc8-5bbf7cfbd0b5)
![image](https://github.com/kubeflow/kubeflow/assets/108779415/2221c31d-181b-4bfe-8cf5-d406be55bfc7)
![image](https://github.com/kubeflow/kubeflow/assets/108779415/713510a4-612c-47e3-b772-2d700f1f521c)
