### ISSUE TITLE
Document the steps for configuring Kubeflow central dashboard behind Traefik

### ISSUE THREAD

**Issue by ahuarte47** [kubeflow/manifests#2784]
### Validation Checklist

- [X] Is this a Kubeflow issue?
- [X] Are you posting in the right repository ?
- [X] Did you follow the installation guide https://github.com/kubeflow/manifests?tab=readme-ov-file ?
- [X] Is the issue report properly structured and detailed with version numbers?
- [ ] Is this for Kubeflow development ?
- [ ] Would you like to work on this issue?
- [ ] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

master

### Describe your issue

When configuring Kubeflow central dashboard behind Traefik, I got errors when loading the static resources.

### Steps to reproduce the issue

1. Deploy Traefik
2. Deploy Kubeflow using manifests as guide shows.
3. Create and apply an IngressRoute... 

```yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: kubeflow-dashboard-strip-prefix
  namespace: istio-system
spec:
  stripPrefix:
    prefixes:
      - /kubeflow5/
    forceSlash: false
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kubeflow-dashboard-ingressroute
  namespace: istio-system
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/protocol: https # Traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: PathPrefix(`/kubeflow5/`)
      services:
        - name: istio-ingressgateway
          namespace: istio-system
          port: 80
      middlewares:
        - name: kubeflow-dashboard-strip-prefix
  tls: {}

``` 

### Put here any screenshots or videos (optional)

https://localhost:9121/app.bundle.js `fails`
https://localhost:9121/kubeflow5/app.bundle.js `works`

![image](https://github.com/kubeflow/manifests/assets/5576272/a1075a69-04de-4407-b520-24b2978d3973)
