### ISSUE TITLE
Unable to set GPU Limit when we want to share an GPU (Timeslicing, MPS...)

### ISSUE THREAD

**Issue by tzabbi** [kubeflow/manifests#2817]
### Validation Checklist

- [X] Is this a Kubeflow issue?
- [X] Are you posting in the right repository ?
- [X] Did you follow the installation guide https://github.com/kubeflow/manifests?tab=readme-ov-file ?
- [X] Is the issue report properly structured and detailed with version numbers?
- [ ] Is this for Kubeflow development ?
- [ ] Would you like to work on this issue?
- [ ] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

master

### Describe your issue

Since Nvidia provide an solution so split one GPU to multiple containers, I need to set this to every notebook by default in "apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml". The proberty to set: 

```yaml
spec:
  containers:
    - name: xxx
      image: xxx
      resources:
        limits:
          nvidia.com/gpu: <number>
```

### Steps to reproduce the issue

Currently not possible to set.
