### ISSUE TITLE
[bug] Jwt issuer is not configured

### ISSUE THREAD

**Issue by jaffe-fly** [kubeflow/manifests#2840]
### Environment
`k8s version v1.29.5`

*  How do you deploy Kubeflow Pipelines (KFP)?
 use kubeflow manifests deploy 1master branch
`git log -1`
```
commit 473b1035304f847063ecaf0a44686182c437db64 (HEAD -> master, origin/v1.9-branch, origin/v1.10-branchorigin/v1.9-branch, origin/v1.10-branch, origin/master, origin/HEAD)
Author: Krzysztof Romanowski <krzysztof.romanowski94@gmail.com>
Date:   Thu Jul 11 14:10:21 2024 +0200

    Fix ml pipeline access from kfp step (#2795)

    * fail gh action if pipeline failed in .github/workflows/pipeline_test.yaml

    Signed-off-by: Krzysztof Romanowski <krzysztof.romanowski.kr1@roche.com>

    * allow access to ml-pipeline when using trusted requestPrincipal or doesn't have auth header

    Signed-off-by: Krzysztof Romanowski <krzysztof.romanowski.kr1@roche.com>

    * add more triggers for the workflow

    Signed-off-by: juliusvonkohout <45896133+juliusvonkohout@users.noreply.github.com>

    ---------

    Signed-off-by: Krzysztof Romanowski <krzysztof.romanowski.kr1@roche.com>
    Signed-off-by: juliusvonkohout <45896133+juliusvonkohout@users.noreply.github.com>
    Co-authored-by: Krzysztof Romanowski <krzysztof.romanowski.kr1@roche.com>
    Co-authored-by: juliusvonkohout <45896133+juliusvonkohout@users.noreply.github.com>
```
*  KFP version:
2.2.0
*  KFP SDK version:
2.7.0
o
### Steps to reproduce
follow this link https://www.kubeflow.org/docs/components/pipelines/user-guides/core-functions/connect-api/#full-kubeflow-subfrom-inside-clustersub

in `my-profile` namespace of kubeflow,and in notebook  `configurations` have add pipeline access token,
code is 
```
from kfp import dsl
client = Client()
print(client.list_experiments(namespace="my-profile"))
```
get following errpr:
```
kfp_server_api.exceptions.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'www-authenticate': 'Bearer realm="http://ml-pipeline.kubeflow.svc.cluster.local:8888/apis/v2beta1/healthz", error="invalid_token"', 'content-length': '28', 'content-type': 'text/plain', 'date': 'Sat, 13 Jul 2024 15:34:54 GMT', 'server': 'envoy', 'x-envoy-upstream-service-time': '1'})
HTTP response body: Jwt issuer is not configured
```

my `poddefault` is
```
apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: access-ml-pipeline
  namespace: my-profile
spec:
  desc: Allow access to Kubeflow Pipelines
  selector:
    matchLabels:
      access-ml-pipeline: "true"
  env:
    - ## this environment variable is automatically read by `kfp.Client()`
      ## this is the default value, but we show it here for clarity
      name: KF_PIPELINES_SA_TOKEN_PATH
      value: /var/run/secrets/kubeflow/pipelines/token
  volumes:
    - name: volume-kf-pipeline-token
      projected:
        sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 7200
              ## defined by the `TOKEN_REVIEW_AUDIENCE` environment variable on the `ml-pipeline` deployment
              audience: pipelines.kubeflow.org
  volumeMounts:
    - mountPath: /var/run/secrets/kubeflow/pipelines
      name: volume-kf-pipeline-token
      readOnly: true
```
my `RoleBinding` is
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-my-profile-kubeflow-edit
  ## this RoleBinding is in `namespace-1`, because it grants access to `namespace-1`
  namespace: kubeflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-edit
subjects:
  - kind: ServiceAccount
    name: default-editor
    ## the ServiceAccount lives in `namespace-2`
    namespace: my-profile
```
### Labels

---

Impacted by this bug? Give it a 👍.
