### ISSUE TITLE
Find an automated way to set JWKS keys in RequestAuthentication for oauth2-proxy M2M (EKS, AKS, GKE, Rancher, Openshift)

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/manifests#2850]
## Related Issues

- https://github.com/kubeflow/manifests/issues/2840
- and numerous people who were previously using KFP SDK from inside the cluster, with ServiceAccount tokens.

## What's the problem?

We have a `RequestAuthentication/m2m-token-issuer` in the `istio-system` namespace which is there to allow Istio to validate JWTs which are actually Kubernetes ServiceAccount tokens. 

This is only relevant to requests to `http://ml-pipeline-ui.kubeflow.svc.cluster.local`, as this is the only place we enforce a `source.requestPrincipals` (see: `AuthorizationPolicy/ml-pipeline` from the `kubeflow` namespace).

### Retrieving the JWKS keys

Currently, we are using a CronJob called `kubeflow-m2m-oidc-configurator` to populate the `jwks` information in the `RequestAuthentication/m2m-token-issuer`: 

- Master: https://github.com/kubeflow/manifests/tree/bf3dd8878af2a52480e60ee90d650a098eacd113/common/oauth2-proxy/components/configure-self-signed-kubernetes-oidc-issuer
- 1.9.0: https://github.com/kubeflow/manifests/tree/v1.9.0/common/oidc-client/oauth2-proxy/components/configure-self-signed-kubernetes-oidc-issuer

This is a bad idea for many reasons as it can result in failures if the JWKS tokens are rotated, or if the strange script fails for any reason (which seems like what is happening on all EKS clusters).

### Setting the correct Issuer

Some clusters don't use `https://kubernetes.default.svc.cluster.local` as their cluster's JWT issuer (notably EKS and GKE), so any RquestAuthentication which assumes this will fail to validate JWTs issued by these clusters.

The only way to know what a cluster's issuer should be is to retrieve it from the `/.well-known/openid-configuration` cluster endpoint.

# What's the solution?

We can instead directly set the `spec.jwtRules[0].jwksUri` of the `RequestAuthentication` to `https://KUBERNETES_API/openid/v1/jwks` as this always serves the cluster's JWSK.

However, the `/openid/v1/jwks` endpoint is not available without authentication (read: accessed by a Pod in the cluster, presenting its ServiceAccount token as authorization).

So as a workaround we can create a `kubectl proxy ...` pod which only exposes this endpoint of the API (note, this is not a security risk, as these are just public signing keys). 

ALSO, in terms of restricting proxy service to specific Pods, I don't think we can easily do that, because each Istio sidecar will need to access it to retrieve the JWSK for its requests.

## 0 - Create the required RBAC

First, create this `ServiceAccount`, `Role`, and `RoleBinding`:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-jwks-proxy
  namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-jwks-proxy
  namespace: istio-system
rules:
  - apiGroups:
      - security.istio.io
    resources:
      - requestauthentications
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-jwks-proxy
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-jwks-proxy
subjects:
  - kind: ServiceAccount
    name: cluster-jwks-proxy
    namespace: istio-system
```

## 1 - Create the Proxy Service

First, create this `Deployment`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-jwks-proxy
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-jwks-proxy
  template:
    metadata:
      labels:
        app: cluster-jwks-proxy
    spec:
      serviceAccountName: cluster-jwks-proxy
      initContainers:
        ## NOTE: clusters don't all use the same JWT 'issuer', so we need to retrieve it from the cluster
        - name: patch-requestauthentication
          image: bitnami/kubectl:1.30.4
          command:
            - /bin/bash
            - -c
          args:
            - |
              # get the issuer from '/.well-known/openid-configuration'
              echo "INFO: Getting cluster issuer from '/.well-known/openid-configuration'"
              ISSUER=$(kubectl get --raw /.well-known/openid-configuration | jq -r '.issuer')
              
              # patch the RequestAuthentication to use the issuer
              RA_NAME="m2m-token-issuer"
              RA_NAMESPACE="istio-system"
              JSON_PATCH=$(cat <<EOF
              [
                {
                  "op": "replace",
                  "path": "/spec/jwtRules/0/issuer",
                  "value": "$ISSUER"
                }
              ]
              EOF
              )
              echo "INFO: Patching RequestAuthentication '$RA_NAME' in '$RA_NAMESPACE' to use issuer '$ISSUER'"
              kubectl patch requestauthentication "$RA_NAME" -n "$RA_NAMESPACE" --type json --patch "$JSON_PATCH"
      containers:
        ## NOTE: some clusters dont make their JWKS endpoint public, so we need to proxy it
        - name: kubectl-proxy
          image: bitnami/kubectl:1.30.4
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            httpGet:
              path: /openid/v1/jwks
              port: http
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            httpGet:
              path: /openid/v1/jwks
              port: http
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            httpGet:
              path: /openid/v1/jwks
              port: http
          args:
            - proxy
            - --address=0.0.0.0
            - --port=8080
            ## accept all hosts (default is local only)
            - --accept-hosts=.*
            ## only accept requests to '/openid/v1/jwks' and '/.well-known/openid-configuration'
            - --accept-paths=^(?:/openid/v1/jwks)|(?:/.well-known/openid-configuration)$
            ## reject all methods except 'GET'
            - --reject-methods=^(POST|PUT|PATCH|DELETE|HEAD|OPTIONS|CONNECT|TRACE)$
```

Next, create this `Service`:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: cluster-jwks-proxy
  namespace: istio-system
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: cluster-jwks-proxy
```

## 2 - Delete existing CronJob

Run this command to delete the `CronJob`:

```bash
kubectl delete cronjob "kubeflow-m2m-oidc-configurator" -n "istio-system"
```

## 3 - Update the RequestAuthentication

Patch the `RequestAuthentication` as follows:

```yaml
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: m2m-token-issuer
  namespace: istio-system
spec:
  jwtRules:
    - forwardOriginalToken: true

      ## \/ this part will be patched by the deployment \/
      issuer: https://kubernetes.default.svc.cluster.local

      ## \/ this part is new, and must be patched manually \/
      jwksUri: http://cluster-jwks-proxy.istio-system.svc.cluster.local/openid/v1/jwks
      
      outputClaimToHeaders:
        - claim: sub
          header: x-auth-request-user
        - claim: sub
          header: kubeflow-userid
```
