### ISSUE TITLE
Swagger UI Not Found Error

### ISSUE THREAD

**Issue by muratyarali** [kubeflow/manifests#2926]
### Validation Checklist

- [X] Is this a Kubeflow issue?
- [X] Are you posting in the right repository ?
- [X] Did you follow the [Kubeflow installation guideline](https://github.com/kubeflow/manifests/blob/master/README.md) ?
- [X] Is the issue report properly structured and detailed with version numbers?
- [X] Is this for Kubeflow development ?
- [X] Would you like to work on this issue?
- [X] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

master

### Describe your issue

Hi Guys.

I need your help about an issue. I think I need to explain the problem in detail for you to understand.

- I want to reach Swagger-UI page of an ISVC with this URL: http://sklearn-iris-predictor.kubeflow-user-example-com.example.com/docs.

But i can not. I am always getting "{"detail":"Not Found"}" Error. I want to ask you that Can firewall block it?

- I created this ISVC in Kubeflow with this file that is given in the documentation
Documentation: https://kserve.github.io/website/latest/get_started/swagger_ui/#inferenceservice-swagger-ui

**What did you expect to happen:**
I want to see Swagger UI page on my browser

**What's the InferenceService yaml:**
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
  namespace: kubeflow-user-example-com
spec:
  predictor:
    model:
      args: ["--enable_docs_url=True"]     # This line allow to reach Swagget-UI
      modelFormat:
        name: sklearn
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
```

### Steps to reproduce the issue

You can follow the documentation mentioned above
