### ISSUE TITLE
`spawner_ui_config.yaml` in `jupyter-web-app` is not being applied

### ISSUE THREAD

**Issue by koh-hr** [kubeflow/manifests#2927]
### Validation Checklist

- [X] Is this a Kubeflow issue?
- [X] Are you posting in the right repository ?
- [X] Did you follow the [Kubeflow installation guideline](https://github.com/kubeflow/manifests/blob/master/README.md) ?
- [X] Is the issue report properly structured and detailed with version numbers?
- [X] Is this for Kubeflow development ?
- [X] Would you like to work on this issue?
- [x] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

1.9

### Describe your issue

I installed the release from the following link:  
https://github.com/kubeflow/manifests/releases/tag/v1.9.1
After adding the settings to the `spawner_ui_config.yaml` in the above release and installing it, I found that the settings were not reflected after logging into Kubeflow.

`spawner_ui_config.yaml`:  
```
# --------------------------------------------------------------
# Configuration file for the Kubeflow Notebooks UI.
#
# About the `readOnly` configs:
#  - when `readOnly` is set to "true", the respective option
#    will be disabled for users and only set by the admin
#  - when 'readOnly' is missing, it defaults to 'false'
# --------------------------------------------------------------

spawnerFormDefaults:
  ################################################################
  # Container Images
  ################################################################
  # if users can input custom images, or only select from dropdowns
  allowCustomImage: true

  # if the registry of the container image is hidden from display
  hideRegistry: true

  # if the tag of the container image is hidden from display
  hideTag: false

  # configs for the ImagePullPolicy
  imagePullPolicy:
    readOnly: false

    # the default ImagePullPolicy
    # (possible values: "Always", "IfNotPresent", "Never")
    value: IfNotPresent

  ################################################################
  # Jupyter-like Container Images
  #
  # NOTES:
  #  - the `image` section is used for "Jupyter-like" apps whose
  #    HTTP path is configured by the "NB_PREFIX" environment variable
  ################################################################
  image:
    # the default container image
    value: kubeflownotebookswg/jupyter-scipy:v1.9.2

    # the list of available container images in the dropdown
    options:
    - kubeflownotebookswg/jupyter-scipy:v1.9.2
    - kubeflownotebookswg/jupyter-pytorch-full:v1.9.2
    - kubeflownotebookswg/jupyter-pytorch-cuda-full:v1.9.2
    - kubeflownotebookswg/jupyter-pytorch-gaudi-full:v1.9.2
    - kubeflownotebookswg/jupyter-tensorflow-full:v1.9.2
    - kubeflownotebookswg/jupyter-tensorflow-cuda-full:v1.9.2

  ################################################################
  # VSCode-like Container Images (Group 1)
  #
  # NOTES:
  #  - the `imageGroupOne` section is used for "VSCode-like" apps that
  #    expose themselves under the HTTP root path "/" and support path
  #    rewriting without breaking
  #  - the annotation `notebooks.kubeflow.org/http-rewrite-uri: "/"` is
  #    set on Notebooks spawned by this group, to make Istio rewrite
  #    the path of HTTP requests to the HTTP root
  ################################################################
   imageGroupOne:
    # the default container image
    value: kubeflownotebookswg/codeserver-python:v1.9.2

    # the list of available container images in the dropdown
    options:
    - kubeflownotebookswg/codeserver-python:v1.9.2

  ################################################################
  # RStudio-like Container Images (Group 2)
  #
  # NOTES:
  #  - the `imageGroupTwo` section is used for "RStudio-like" apps whose
  #    HTTP path is configured by the "X-RStudio-Root-Path" header
  #  - the annotation `notebooks.kubeflow.org/http-rewrite-uri: "/"` is
  #    set on Notebooks spawned by this group, to make Istio rewrite
  #    the path of HTTP requests to the HTTP root
  #  - the annotation `notebooks.kubeflow.org/http-headers-request-set` is
  #    set on Notebooks spawned by this group, such that Istio injects the
  #    "X-RStudio-Root-Path" header to all request
  ################################################################
  imageGroupTwo:
    # the default container image
    value: kubeflownotebookswg/rstudio-tidyverse:v1.9.2

    # the list of available container images in the dropdown
    options:
    - kubeflownotebookswg/rstudio-tidyverse:v1.9.2

  ################################################################
  # CPU Resources
  ################################################################
  cpu:
    readOnly: false

    # the default cpu request for the container
    value: "0.5"

    # a factor by which to multiply the CPU request calculate the cpu limit
    # (to disable cpu limits, set as "none")
    limitFactor: "1.2"

  ################################################################
  # Memory Resources
  ################################################################
  memory:
    readOnly: false

    # the default memory request for the container
    value: "1.0Gi"

    # a factor by which to multiply the memory request calculate the memory limit
    # (to disable memory limits, set as "none")
    limitFactor: "1.2"

  ################################################################
  # GPU/Device-Plugin Resources
  ################################################################
  gpus:
    readOnly: false

    # configs for gpu/device-plugin limits of the container
    # https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/#using-device-plugins
    value:
      # the `limitKey` of the default vendor
      # (to have no default, set as "")
      vendor: ""

      # the list of available vendors in the dropdown
      #  `limitsKey` - what will be set as the actual limit
      #  `uiName` - what will be displayed in the dropdown UI
      vendors:
      - limitsKey: "nvidia.com/gpu"
        uiName: "NVIDIA"
      - limitsKey: "amd.com/gpu"
        uiName: "AMD"
      - limitsKey: "habana.ai/gaudi"
        uiName: "Intel Gaudi"

      # the default value of the limit
      # (possible values: "none", "1", "2", "4", "8")
      num: "none"

  ################################################################
  # Workspace Volumes
  ################################################################
  workspaceVolume:
    readOnly: false

    # the default workspace volume to be created and mounted
    # (to have no default, set `value: null`)
    value:
      mount: /home/jovyan

      # pvc configs for creating new workspace volumes
      # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#persistentvolumeclaim-v1-core
      newPvc:
        metadata:
          # "{notebook-name}" is replaced with the Notebook name
          name: "{notebook-name}-workspace"
        spec:
          #storageClassName: my-storage-class
          resources:
            requests:
              storage: 5Gi
          accessModes:
          - ReadWriteOnce

  ################################################################
  # Data Volumes
  ################################################################
  dataVolumes:
    readOnly: false

    # a list of additional data volumes to be created and/or mounted
    value: []
    #value:
    #  - mount: /home/jovyan/datavol-1
    #    newPvc:
    #      metadata:
    #        name: "{notebook-name}-datavol-1"
    #      spec:
    #        resources:
    #          requests:
    #            storage: 5Gi
    #        accessModes:
    #          - ReadWriteOnce
    #
    #  - mount: /home/jovyan/datavol-1
    #    existingSource:
    #      persistentVolumeClaim:
    #        claimName: "test-pvc"

  ################################################################
  # Affinity
  ################################################################
  affinityConfig:
    readOnly: false

    # the `configKey` of the default affinity config
    # (to have no default, set as "")
    # (if `readOnly`, the default `value` will be the only accessible option)
    # value: ""

    value: "default"

    # the list of available affinity configs in the dropdown
    #options: []
    options:
      - configKey: "default"
        displayName: "Select 16 or 32 for GPUs 2 and above"     
        affinity:
          nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
               - matchExpressions:
                   - key: "nodetype"
                     operator: "In"
                     values:
                      - "worker"
      - configKey: "16GB"
        displayName: "16GB"
        affinity:
    #      # (Require) Node having label: `memorysize=16GB`
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: "memorysize"
                      operator: "In"
                      values:
                       - "16GB"
      - configKey: "20GB"
        displayName: "20GB"
        affinity:
    #      # (Require) Node having label: `memorysize=20GB`
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: "memorysize"
                      operator: "In"
                      values:
                       - "20GB"
    #options:
    #  - configKey: "dedicated_node_per_notebook"
    #    displayName: "Dedicated Node Per Notebook"
    #    affinity:
    #      # Require a Node with label `lifecycle=kubeflow-notebook`
    #      nodeAffinity:
    #        requiredDuringSchedulingIgnoredDuringExecution:
    #          nodeSelectorTerms:
    #            - matchExpressions:
    #                - key: "lifecycle"
    #                  operator: "In"
    #                  values:
    #                    - "kubeflow-notebook"
    #
    #      # Require a Node WITHOUT an existing Pod having `notebook-name` label
    #      podAntiAffinity:
    #        requiredDuringSchedulingIgnoredDuringExecution:
    #          - labelSelector:
    #              matchExpressions:
    #                - key: "notebook-name"
    #                  operator: "Exists"
    #            topologyKey: "kubernetes.io/hostname"
    #            # WARNING: `namespaceSelector` is Beta in 1.22 and Stable in 1.24,
    #            #          setting to {} is required for affinity to work across Namespaces
    #            namespaceSelector: {}

  ################################################################
  # Tolerations
  ################################################################
  tolerationGroup:
    readOnly: false

    # the `groupKey` of the default toleration group
    # (to have no default, set as "")
    # (if `readOnly`, the default `value` will be the only accessible option)
    value: ""

    # the list of available toleration groups in the dropdown
    options: []
    #options:
    #  - groupKey: "group_1"
    #    displayName: "4 CPU 8Gb Mem at ~$X.XXX USD per day"
    #    tolerations:
    #      - key: "dedicated"
    #        operator: "Equal"
    #        value: "kubeflow-c5.xlarge"
    #        effect: "NoSchedule"
    #
    #  - groupKey: "group_2"
    #    displayName: "8 CPU 16Gb Mem at ~$X.XXX USD per day"
    #    tolerations:
    #      - key: "dedicated"
    #        operator: "Equal"
    #        value: "kubeflow-c5.2xlarge"
    #        effect: "NoSchedule"
    #
    #  - groupKey: "group_3"
    #    displayName: "16 CPU 32Gb Mem at ~$X.XXX USD per day"
    #    tolerations:
    #      - key: "dedicated"
    #        operator: "Equal"
    #        value: "kubeflow-c5.4xlarge"
    #        effect: "NoSchedule"
    #
    #  - groupKey: "group_4"
    #    displayName: "32 CPU 256Gb Mem at ~$X.XXX USD per day"
    #    tolerations:
    #      - key: "dedicated"
    #        operator: "Equal"
    #        value: "kubeflow-r5.8xlarge"
    #        effect: "NoSchedule"

  ################################################################
  # Shared Memory
  ################################################################
  shm:
    readOnly: false

    # the default state of the "Enable Shared Memory" toggle
    value: true

  ################################################################
  # PodDefaults
  ################################################################
  configurations:
    readOnly: false

    # the list of PodDefault names that are selected by default
    # (take care to ensure these PodDefaults exist in Profile Namespaces)
    value: []
    #value:
    #  - my-pod-default

  ################################################################
  # Environment
  #
  # NOTE:
  #  - these configs are only used by the ROK "flavor" of the UI
  ################################################################
  environment:
    readOnly: false
    value: {}

```

The specific issues are as follows:
- The notebook image is set to "latest."
- The affinity settings are not being applied.

<img width="786" alt="スクリーンショット 2024-11-28 15 49 54" src="https://github.com/user-attachments/assets/a2edc243-2fed-4c55-8450-5a0561422c7e">
<img width="806" alt="スクリーンショット 2024-11-28 15 55 40" src="https://github.com/user-attachments/assets/7392bfc4-4276-40b3-8e61-e56b55c2e6da">

I checked the deployed Pods and the mounted configmaps, and I confirmed that the settings are correctly applied. However, they are not reflected in the UI.

- pod
```
$ kubectl describe pod -n kubeflow jupyter-web-app-deployment-68bb6bcc96-9rjq7
Name:             jupyter-web-app-deployment-68bb6bcc96-9rjq7
Namespace:        kubeflow
Priority:         0
Service Account:  jupyter-web-app-service-account
・・・
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      jupyter-web-app-config-tg99dfh27f
    Optional:  false
```
- configmap
```
$ kubectl describe cm -n kubeflow jupyter-web-app-config-tg99dfh27f
Name:         jupyter-web-app-config-tg99dfh27f
Namespace:    kubeflow
Labels:       app=jupyter-web-app
              kustomize.component=jupyter-web-app
Annotations:  <none>

Data
====
spawner_ui_config.yaml:
----
# --------------------------------------------------------------
# Configuration file for the Kubeflow Notebooks UI.
#
# About the `readOnly` configs:
#  - when `readOnly` is set to "true", the respective option
#    will be disabled for users and only set by the admin
#  - when 'readOnly' is missing, it defaults to 'false'
# --------------------------------------------------------------

spawnerFormDefaults:
  ################################################################
  # Container Images
  ################################################################
  # if users can input custom images, or only select from dropdowns
  allowCustomImage: true

  # if the registry of the container image is hidden from display
  hideRegistry: true

  # if the tag of the container image is hidden from display
  hideTag: false

  # configs for the ImagePullPolicy
  imagePullPolicy:
    readOnly: false

    # the default ImagePullPolicy
    # (possible values: "Always", "IfNotPresent", "Never")
    value: IfNotPresent

  ################################################################
  # Jupyter-like Container Images
  #
  # NOTES:
  #  - the `image` section is used for "Jupyter-like" apps whose
  #    HTTP path is configured by the "NB_PREFIX" environment variable
  ################################################################
  image:
    # the default container image
    value: kubeflownotebookswg/jupyter-scipy:v1.9.2

    # the list of available container images in the dropdown
    options:
    - kubeflownotebookswg/jupyter-scipy:v1.9.2
    - kubeflownotebookswg/jupyter-pytorch-full:v1.9.2
    - kubeflownotebookswg/jupyter-pytorch-cuda-full:v1.9.2
    - kubeflownotebookswg/jupyter-pytorch-gaudi-full:v1.9.2
    - kubeflownotebookswg/jupyter-tensorflow-full:v1.9.2
    - kubeflownotebookswg/jupyter-tensorflow-cuda-full:v1.9.2

  ################################################################
  # VSCode-like Container Images (Group 1)
  #
  # NOTES:
  #  - the `imageGroupOne` section is used for "VSCode-like" apps that
  #    expose themselves under the HTTP root path "/" and support path
  #    rewriting without breaking
  #  - the annotation `notebooks.kubeflow.org/http-rewrite-uri: "/"` is
  #    set on Notebooks spawned by this group, to make Istio rewrite
  #    the path of HTTP requests to the HTTP root
  ################################################################
   imageGroupOne:
    # the default container image
    value: kubeflownotebookswg/codeserver-python:v1.9.2

    # the list of available container images in the dropdown
    options:
    - kubeflownotebookswg/codeserver-python:v1.9.2

  ################################################################
  # RStudio-like Container Images (Group 2)
  #
  # NOTES:
  #  - the `imageGroupTwo` section is used for "RStudio-like" apps whose
  #    HTTP path is configured by the "X-RStudio-Root-Path" header
  #  - the annotation `notebooks.kubeflow.org/http-rewrite-uri: "/"` is
  #    set on Notebooks spawned by this group, to make Istio rewrite
  #    the path of HTTP requests to the HTTP root
  #  - the annotation `notebooks.kubeflow.org/http-headers-request-set` is
  #    set on Notebooks spawned by this group, such that Istio injects the
  #    "X-RStudio-Root-Path" header to all request
  ################################################################
  imageGroupTwo:
    # the default container image
    value: kubeflownotebookswg/rstudio-tidyverse:v1.9.2

    # the list of available container images in the dropdown
    options:
    - kubeflownotebookswg/rstudio-tidyverse:v1.9.2

  ################################################################
  # CPU Resources
  ################################################################
  cpu:
    readOnly: false

    # the default cpu request for the container
    value: "0.5"

    # a factor by which to multiply the CPU request calculate the cpu limit
    # (to disable cpu limits, set as "none")
    limitFactor: "1.2"

  ################################################################
  # Memory Resources
  ################################################################
  memory:
    readOnly: false

    # the default memory request for the container
    value: "1.0Gi"

    # a factor by which to multiply the memory request calculate the memory limit
    # (to disable memory limits, set as "none")
    limitFactor: "1.2"

  ################################################################
  # GPU/Device-Plugin Resources
  ################################################################
  gpus:
    readOnly: false

    # configs for gpu/device-plugin limits of the container
    # https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/#using-device-plugins
    value:
      # the `limitKey` of the default vendor
      # (to have no default, set as "")
      vendor: ""

      # the list of available vendors in the dropdown
      #  `limitsKey` - what will be set as the actual limit
      #  `uiName` - what will be displayed in the dropdown UI
      vendors:
      - limitsKey: "nvidia.com/gpu"
        uiName: "NVIDIA"
      - limitsKey: "amd.com/gpu"
        uiName: "AMD"
      - limitsKey: "habana.ai/gaudi"
        uiName: "Intel Gaudi"

      # the default value of the limit
      # (possible values: "none", "1", "2", "4", "8")
      num: "none"

  ################################################################
  # Workspace Volumes
  ################################################################
  workspaceVolume:
    readOnly: false

    # the default workspace volume to be created and mounted
    # (to have no default, set `value: null`)
    value:
      mount: /home/jovyan

      # pvc configs for creating new workspace volumes
      # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#persistentvolumeclaim-v1-core
      newPvc:
        metadata:
          # "{notebook-name}" is replaced with the Notebook name
          name: "{notebook-name}-workspace"
        spec:
          #storageClassName: my-storage-class
          resources:
            requests:
              storage: 5Gi
          accessModes:
          - ReadWriteOnce

  ################################################################
  # Data Volumes
  ################################################################
  dataVolumes:
    readOnly: false

    # a list of additional data volumes to be created and/or mounted
    value: []
    #value:
    #  - mount: /home/jovyan/datavol-1
    #    newPvc:
    #      metadata:
    #        name: "{notebook-name}-datavol-1"
    #      spec:
    #        resources:
    #          requests:
    #            storage: 5Gi
    #        accessModes:
    #          - ReadWriteOnce
    #
    #  - mount: /home/jovyan/datavol-1
    #    existingSource:
    #      persistentVolumeClaim:
    #        claimName: "test-pvc"

  ################################################################
  # Affinity
  ################################################################
  affinityConfig:
    readOnly: false

    # the `configKey` of the default affinity config
    # (to have no default, set as "")
    # (if `readOnly`, the default `value` will be the only accessible option)
    # value: ""

    value: "default"

    # the list of available affinity configs in the dropdown
    #options: []
    options:
      - configKey: "default"
        displayName: "Select 16 or 32 for GPUs 2 and above"
        affinity:
          nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
               - matchExpressions:
                   - key: "nodetype"
                     operator: "In"
                     values:
                      - "worker"
      - configKey: "16GB"
        displayName: "16GB"
        affinity:
    #      # (Require) Node having label: `memorysize=16GB`
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: "memorysize"
                      operator: "In"
                      values:
                       - "16GB"
      - configKey: "20GB"
        displayName: "20GB"
        affinity:
    #      # (Require) Node having label: `memorysize=20GB`
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: "memorysize"
                      operator: "In"
                      values:
                       - "20GB"
    #options:
    #  - configKey: "dedicated_node_per_notebook"
    #    displayName: "Dedicated Node Per Notebook"
    #    affinity:
    #      # Require a Node with label `lifecycle=kubeflow-notebook`
    #      nodeAffinity:
    #        requiredDuringSchedulingIgnoredDuringExecution:
    #          nodeSelectorTerms:
    #            - matchExpressions:
    #                - key: "lifecycle"
    #                  operator: "In"
    #                  values:
    #                    - "kubeflow-notebook"
    #
    #      # Require a Node WITHOUT an existing Pod having `notebook-name` label
    #      podAntiAffinity:
    #        requiredDuringSchedulingIgnoredDuringExecution:
    #          - labelSelector:
    #              matchExpressions:
    #                - key: "notebook-name"
    #                  operator: "Exists"
    #            topologyKey: "kubernetes.io/hostname"
    #            # WARNING: `namespaceSelector` is Beta in 1.22 and Stable in 1.24,
    #            #          setting to {} is required for affinity to work across Namespaces
    #            namespaceSelector: {}

  ################################################################
  # Tolerations
  ################################################################
  tolerationGroup:
    readOnly: false

    # the `groupKey` of the default toleration group
    # (to have no default, set as "")
    # (if `readOnly`, the default `value` will be the only accessible option)
    value: ""

    # the list of available toleration groups in the dropdown
    options: []
    #options:
    #  - groupKey: "group_1"
    #    displayName: "4 CPU 8Gb Mem at ~$X.XXX USD per day"
    #    tolerations:
    #      - key: "dedicated"
    #        operator: "Equal"
    #        value: "kubeflow-c5.xlarge"
    #        effect: "NoSchedule"
    #
    #  - groupKey: "group_2"
    #    displayName: "8 CPU 16Gb Mem at ~$X.XXX USD per day"
    #    tolerations:
    #      - key: "dedicated"
    #        operator: "Equal"
    #        value: "kubeflow-c5.2xlarge"
    #        effect: "NoSchedule"
    #
    #  - groupKey: "group_3"
    #    displayName: "16 CPU 32Gb Mem at ~$X.XXX USD per day"
    #    tolerations:
    #      - key: "dedicated"
    #        operator: "Equal"
    #        value: "kubeflow-c5.4xlarge"
    #        effect: "NoSchedule"
    #
    #  - groupKey: "group_4"
    #    displayName: "32 CPU 256Gb Mem at ~$X.XXX USD per day"
    #    tolerations:
    #      - key: "dedicated"
    #        operator: "Equal"
    #        value: "kubeflow-r5.8xlarge"
    #        effect: "NoSchedule"

  ################################################################
  # Shared Memory
  ################################################################
  shm:
    readOnly: false

    # the default state of the "Enable Shared Memory" toggle
    value: true

  ################################################################
  # PodDefaults
  ################################################################
  configurations:
    readOnly: false

    # the list of PodDefault names that are selected by default
    # (take care to ensure these PodDefaults exist in Profile Namespaces)
    value: []
    #value:
    #  - my-pod-default

  ################################################################
  # Environment
  #
  # NOTE:
  #  - these configs are only used by the ROK "flavor" of the UI
  ################################################################
  environment:
    readOnly: false
    value: {}


BinaryData
====

Events:  <none>
```

Everything worked fine in v1.8, but the settings are not being applied in v1.9.  
I would appreciate it if you could guide me on how to resolve this issue.

### Steps to reproduce the issue

1. Change the reference to the `Jupyter Web App` in `kustomization.yaml` as follows.
```
# Jupyter Web App
#- ../apps/jupyter/jupyter-web-app/upstream/overlays/istio
- jupyter-web-app-config-files/
```
2. Set the reference directory as follows.
```
# ls -l jupyter-web-app-config-files
total 40
-rw-r--r--  1 koh  staff    424 10  8 13:49 kustomization.yaml
-rw-r--r--  1 koh  staff  12364 11 26 17:40 spawner_ui_config.yaml

# cat jupyter-web-app-config-files/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../apps/jupyter/jupyter-web-app/upstream/overlays/istio
namespace: kubeflow
commonLabels:
  app: jupyter-web-app
  kustomize.component: jupyter-web-app
configMapGenerator:
- files:
  - spawner_ui_config.yaml
  behavior: merge
  name: config

# cat jupyter-web-app-config-files/spawner_ui_config.yaml
# --------------------------------------------------------------
# Configuration file for the Kubeflow Notebooks UI.
#
# About the `readOnly` configs:
#  - when `readOnly` is set to "true", the respective option
#    will be disabled for users and only set by the admin
#  - when 'readOnly' is missing, it defaults to 'false'
# --------------------------------------------------------------
・・・
```
3. Install using `kustomize`.

**Comment by LehmBook** [comment]
After the file'spawner_ui_config.yaml' you need to reapply it with kustomize

**Comment by juliusvonkohout** [comment]
Does this happen in a clean kind cluster with a freshly installed kubeflow 1.9.1/master as described in the main readme?

**Comment by koh-hr** [comment]
@LehmBook 
> After the file'spawner_ui_config.yaml' is configged, you need to reapply it with kustomize again so it loaded

Thank you for your response!
I tried reapplying kustomize, but unfortunately, it didn’t resolve the issue.

Just in case, I also performed a rollout restart on the deployment and edited the configuration to mount a new ConfigMap, but the result was the same.

**Comment by LehmBook** [comment]
Frist of all,im no pro in kubeflow. And Im currently trying 1.9.1 out. so I tried the code as follow:
```
  ################################################################
  # Affinity
  ################################################################
  affinityConfig:
    readOnly: false

    # the `configKey` of the default affinity config
    # (to have no default, set as "")
    # (if `readOnly`, the default `value` will be the only accessible option)
    value: ""

    # the list of available affinity configs in the dropdown
    #options: []
    options:
      - configKey: "dedicated_node_per_notebook"
        displayName: "Dedicated Node Per Notebook"
        affinity:
    #      # Require a Node with label `lifecycle=kubeflow-notebook`
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: "lifecycle"
                      operator: "In"
                      values:
                        - "kubeflow-notebook"
      - configKey: "16GB"
        displayName: "16GB"
        affinity:
    #      # (Require) Node having label: `memorysize=16GB`
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: "memorysize"
                      operator: "In"
                      values:
                       - "16GB"
```
In my UI, it shows as follow,
![1733108837512](https://github.com/user-attachments/assets/a833ea51-409f-4405-9062-a0f7d05b1d24)
![1733108880960](https://github.com/user-attachments/assets/8184749b-9285-4d0b-879d-586ec825e614)
the only difference from the code i can see is:
you are using  `  value: "default"`
mine is      ` value: ""`

**Comment by LehmBook** [comment]
@koh-hr if the problem does not resolved. You may wanna try jupyter-web-app:v1.9.1(or other versions) instead of 1.9.2 by adding following lines in the ../examples/kustomization.yaml and reapply it
```
...
# Training Operator
- ../apps/training-operator/upstream/overlays/kubeflow
# User namespace
- ../common/user-namespace/base

# KServe
- ../contrib/kserve/kserve
- ../contrib/kserve/models-web-app/overlays/kubeflow
....
  - name: docker.io/kubeflownotebookswg/jupyter-web-app
    newName: docker.io/kubeflownotebookswg/jupyter-web-app
    newTag: "v1.9.1"
```

**Comment by koh-hr** [comment]
Thank you for your debugging efforts.
We have identified the root cause.

The issue was caused by extra spaces before the newline characters in the commented-out lines of the `spawner_ui_config.yaml` file, which was modified using kustomize. This resulted in an incorrect configuration of the data in the ConfigMap.
```
# ls -l jupyter-web-app-config-files
total 40
-rw-r--r--  1 koh  staff    424 10  8 13:49 kustomization.yaml
-rw-r--r--  1 koh  staff  12364 11 26 17:40 spawner_ui_config.yaml

# cat jupyter-web-app-config-files/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../apps/jupyter/jupyter-web-app/upstream/overlays/istio
namespace: kubeflow
commonLabels:
  app: jupyter-web-app
  kustomize.component: jupyter-web-app
configMapGenerator:
- files:
  - spawner_ui_config.yaml
  behavior: merge
  name: config

# cat jupyter-web-app-config-files/spawner_ui_config.yaml
# --------------------------------------------------------------
# Configuration file for the Kubeflow Notebooks UI.
#
# About the `readOnly` configs:
#  - when `readOnly` is set to "true", the respective option
#    will be disabled for users and only set by the admin
#  - when 'readOnly' is missing, it defaults to 'false'
# --------------------------------------------------------------
・・・
```

We appreciate your time and effort in assisting with this issue.
I will go ahead and close this issue now.
