### ISSUE TITLE
mysql pod never starts

### ISSUE THREAD

**Issue by pedrovgp** [kubeflow/manifests#2978]
### Validation Checklist

- [x] Is this a Kubeflow issue?
- [x] Are you posting in the right repository ?
- [x] Did you follow the [Kubeflow installation guideline](https://github.com/kubeflow/manifests/blob/master/README.md) ?
- [x] Is the issue report properly structured and detailed with version numbers?
- [ ] Is this for Kubeflow development ?
- [ ] Would you like to work on this issue?
- [ ] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

master

### Describe your issue

I am installing Kubeflow 1.10rc0 in Kubernetes (EKS) 1.30.

I customized storageclasses to leverage ebs in AWS. My storageclass(es) are below.

The default (auto-ebs-sc) was used for all PVC, mysql included. 

```yaml
# storageclass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
parameters:
  fsType: ext4
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: auto-ebs-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.eks.amazonaws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  encrypted: "true"
allowVolumeExpansion: true
```

I followed the instructions, almost all pods are up, except for mysql and those dependent on it (metadata-grpc-deployment, metadata-writer, minio, ml-pipeline).

Checking the logs of mysql, it shows:
```
│ mysql 2025-02-05 19:05:13+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.26-1debian10 started.                                                                                                                                                       │
│ mysql 2025-02-05 19:05:13+00:00 [Note] [Entrypoint]: Initializing database files                                                                                                                                                                                        │
│ mysql mysqld: Can't create/write to file '/var/lib/mysql/is_writable' (OS errno 13 - Permission denied)                                                                                                                                                                 │
│ mysql 2025-02-05T19:05:13.251478Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.26) initializing of server in progress as process 22                                                                                                                     │
│ mysql 2025-02-05T19:05:13.252659Z 0 [ERROR] [MY-010460] [Server] --initialize specified but the data directory exists and is not writable. Aborting.                                                                                                                    │
│ mysql 2025-02-05T19:05:13.252666Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.                                                                                       │
│ mysql 2025-02-05T19:05:13.252710Z 0 [ERROR] [MY-010119] [Server] Aborting                                                                                                                                                                                               │
│ mysql 2025-02-05T19:05:13.252845Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.26)  MySQL Community Server - GPL.             
```

I checked the deployment manifest, [it recommends removing a directory inside the mysql pod](https://github.com/kubeflow/manifests/blob/master/apps/pipeline/upstream/third-party/mysql/base/mysql-deployment.yaml#L25).

But the pod is never up, so there is not way to open the bash in it and remove that directory.

### Steps to reproduce the issue

1. Checkout the v1.10rc0 branch.
2. Create an EKS cluster in Kubernetes 1.30 version.
3. Configure the cluster to be used by kubectl.
4. Run `kubectl apply -k example`
5. Apply the custom storage classes.

**Comment by juliusvonkohout** [comment]
CC @rimolive @varodrig @kubeflow/release-team 

@pedrovgp are you following our instructions with a KIND cluster as you checked the checkbox for https://github.com/kubeflow/manifests/blob/master/README.md. Because is see you mentioning EKS instead.

**Comment by pedrovgp** [comment]
I am using EKS, but the guide is a good reference to it. One thing I forgot to mention though (I'll edit in the description), is that I customized storageclasses to leverage ebs in AWS. My storageclass(es) are below.

The default (auto-ebs-sc) was used for all PVC, mysql included. 

```yaml
# storageclass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
parameters:
  fsType: ext4
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: auto-ebs-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.eks.amazonaws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  encrypted: "true"
allowVolumeExpansion: true
```
