### ISSUE TITLE
HPA and PDB are dropped for istio-ingressgateway

### ISSUE THREAD

**Issue by fraenkel** [kubeflow/manifests#3035]
### Validation Checklist

- [x] I confirm that this is a Kubeflow-related issue.
- [x] I am reporting this in the appropriate repository.
- [x] I have followed the [Kubeflow installation guidelines](https://github.com/kubeflow/manifests/blob/master/README.md).
- [x] The issue report is detailed and includes version numbers where applicable.
- [ ] This issue pertains to Kubeflow development.
- [ ] I am available to work on this issue.
- [ ] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

master

### Detailed Description

The latest istio 1.24.x manifests have dropped the HorizontalPodAutoScaler and PodDisruptionBudget for istio-ingressgateway.
This was present in prior Kubeflow releases.

### Steps to Reproduce

The existing install.yaml only contains HPA and PDB for istiod. 
If you perform a `istioctl manifest generate -f profile.yaml` they appear.
When the `profile-overlay.yaml` is applied, it disappears.

By adding
```
   components:
     ingressGateways:
+      - enabled: true
+        name: istio-ingressgateway
       # Cluster-local gateway for KFServing
       - enabled: true
         name: cluster-local-gateway
```
it appears again.
Lists are replaced not merged.
