### ISSUE TITLE
How do we manually verify that the expected value in the unittests is correct?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#306]
How are we supposed to verify that the expected values used by unittests is correct?

As an example:  kubeflow/kubeflow#3986 appears to be due to a bug in the kustomize manifest resulting in environment variables not being set correctly to the variable value; instead they remained set to the variable name e.g. `$(userid-prefix)

I would expect this is something we test in the unittest. 

So my expectation would be that I can look at the unittest and verify by inspection that the expected value is what it should be.

But when I look at the unittest
https://github.com/kubeflow/manifests/blob/76bd875d65d39960ab2d75daa2ba2b7a2a9e82a4/tests/centraldashboard-base_test.go#L76

It looks like we are specifying the kustomize files (i.e. the input) and not the expected output.
For example here:
https://github.com/kubeflow/manifests/blob/76bd875d65d39960ab2d75daa2ba2b7a2a9e82a4/tests/jupyter-web-app-base_test.go#L242

We are setting

```
        image: gcr.io/kubeflow-images-public/jupyter-web-app:v0.5.0
        imagePullPolicy: $(policy)
```

The expected value for imagePullPolicy should not be $(policy). So either that is the input value and not the expected value or else our tests are wrong.

Can someone familiar with the unittest infrastructure help educate me?

My expectation is that unittests would work as follows

* A golden set of manifests for different scenarios would be checked in somewhere (either as go code or as separate files in a "golden") directory
   * Thus I can look at those golden files to see if the expected value is what it should be
* The tests would be comparing the generated files to the golden files.
* There might be some scripts or utilities to regenerate the golden files (e.g. by running kustomize)
    * During code review it should be easy to inspect the diff to the golden files to allow manual verification of the new golden data

/cc @johnugeorge @yanniszark @kkasravi

**Comment by jlewi** [comment]
What is this code doing?
https://github.com/kubeflow/manifests/blob/76bd875d65d39960ab2d75daa2ba2b7a2a9e82a4/tests/jupyter-web-app-base_test.go#L451

Looks like we are running kustomize to get the expected value.

**Comment by kkasravi** [comment]
if values aren't replaced and one or more warnings are emitted 
```
2019/08/23 12:29:59 well-defined vars that were never replaced: clusterDomain
```
we should FAIL on that unit test.

**Comment by kkasravi** [comment]
@jlewi I've opened #308 PTAL

**Comment by jlewi** [comment]
thanks @kkasravi 

> generate should be called for all supported config files

What is a support config file in this case? Do you mean all support KfDef YAML files?

All of your comments sound like sound improvements. I'm still not clear how we would ensure that the expected values are correct.

How do we fix the unittests so that its easy to verify by manual inspection that the expected values are correct?

**Comment by kkasravi** [comment]
As far as vars go - it would be easy to grep for '\$(' values

**Comment by jlewi** [comment]
How does grepping for "$(" allow me to verify that the expected output is correct?

Shouldn't the unittests be doing something like taking a kustomization.yaml, params.env as input running kustomize build and then ensuring the generated output matches some expected golden output?

Here's the deployment for the profiles controller
https://github.com/kubeflow/manifests/blob/master/profiles/base/deployment.yaml

It has several variables e.g. $(userid-header) in the command line argument.

So my expectation is that using the unittest I can verify that kustomize is correctly substituting in the correct values for those variables and generating the appropriate command line argument.

Looking at the unittest 
https://github.com/kubeflow/manifests/blob/master/tests/profiles-base_test.go

How can I verify that the expected value that the unittest is testing against is what I expect? I'd like to be able to inspect the unittest and verify that the unittest is using an expected value that ensures the parameters are correctly substituted.  I'd expect that by looking at the unittest I could see that the input was params.env with $(userid-header) set to some value e.g. "fake-header" and that the expected value for the deployment had a command line like

```
 args:
       ....
        - "-userid-header"
        - fake-header       
```

**Comment by kkasravi** [comment]
so some kind of output like 

```
admin=xxxx
userid-header=yyyy
userid-prefix=zzzz
```

and 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
      - command:
        - /manager
        args:
        - "-userid-header"
        - yyyy
        - "-userid-prefix"
        - zzzz
        image: gcr.io/kubeflow-images-public/profile-controller:v20190619-v0-219-gbd3daa8c-dirty-1ced0e
        imagePullPolicy: Always
        name: manager
      - command:
        - /opt/kubeflow/access-management
        args:
        - "-cluster-admin"
        - xxxx
        - "-userid-header"
        - yyyy
        - "-userid-prefix"
        - zzzz
        image: gcr.io/kubeflow-images-public/kfam:v20190612-v0-170-ga06cdb79-dirty-a33ee4
        imagePullPolicy: Always
        name: kfam
      serviceAccountName: controller-service-account
```

with the substitutions in red or something?
