### ISSUE TITLE
/jupyter/ is not a valid page - v1.10.0

### ISSUE THREAD

**Issue by IgnisMagister** [kubeflow/manifests#3089]
### Validation Checklist

- [x] I confirm that this is a Kubeflow-related issue.
- [x] I am reporting this in the appropriate repository.
- [x] I have followed the [Kubeflow installation guidelines](https://github.com/kubeflow/manifests/blob/master/README.md).
- [x] The issue report is detailed and includes version numbers where applicable.
- [ ] This issue pertains to Kubeflow development.
- [ ] I am available to work on this issue.
- [ ] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

master

### Detailed Description

I just deployed Kubeflow on my single-node Kubernetes by following the installation guidelines via the "Install Individual Components" chapter.

When I tried to access the Notebook tab, I was greeted by the following error message : "Sorry, /jupyter/ is not a valid page".

I used the tag v1.10.0 to clone and install. (`git clone https://github.com/kubeflow/manifests.git -b v1.10.0 --single-branch`)
I modified some files from the git repository that I cloned.
I changed the default user email and password.
Impacted files :
- `common/dex/base/dex-passwords.yaml`
- `common/user-namespace/base/params.env`
- `common/dex/overlays/oauth2-proxy/config-map.yaml`

I also changed the PVC for Katib's MySQL, I use NFS as a volume provider and MySQL as incompatibilities due to uid/gid. I added a PersistentVolume mounted directly on the filesystem of a node and attributed its storage class to the PVC "katib-mysql".
Impacted file : `apps/katib/upstream/components/mysql/pvc.yaml`
Content:

```yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: katib-mysql-hostpath-volume
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: katib-mysql-hostpath-class
  local:
    path: /hostpaths/katib-mysql-hostpath-volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - <hostname_to_be_replaced>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: katib-mysql
  namespace: kubeflow
spec:
  storageClassName: katib-mysql-hostpath-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

All Pods are Running or Completed.

### Steps to Reproduce

- Clone the git with tag v1.10.0,
- Modify the email and password of the default user in the files in the detailed description,
- Change the "katib-mysql" PVC to use a PV with `volumeMode: filesystem`, `accessMode: RWO`, `nodeAffinity` to a specified hostname (the only one in my cluster for my case),
- Follow the _Install Individual Components_ procedure.
