### ISSUE TITLE
The EnvoyFilter rule named authn-filter redirects all my Gateways to authservice

### ISSUE THREAD

**Issue by ZYWNB666** [kubeflow/manifests#3104]
### Validation Checklist

- [x] I confirm that this is a Kubeflow-related issue.
- [x] I am reporting this in the appropriate repository.
- [x] I have followed the [Kubeflow installation guidelines](https://github.com/kubeflow/manifests/blob/master/README.md).
- [x] The issue report is detailed and includes version numbers where applicable.
- [x] This issue pertains to Kubeflow development.
- [ ] I am available to work on this issue.
- [ ] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

v1.6.1

### Detailed Description

The EnvoyFilter rule named authn-filter redirects all my Gateways to authservice
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authn-filter
  namespace: istio-system
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.http_connection_manager
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.ext_authz
          typed_config:
            '@type': >-
              type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            http_service:
              authorization_request:
                allowed_headers:
                  patterns:
                    - exact: authorization
                    - exact: cookie
                    - exact: x-auth-token
              authorization_response:
                allowed_upstream_headers:
                  patterns:
                    - exact: kubeflow-userid
              server_uri:
                cluster: outbound|8080||authservice.istio-system.svc.cluster.local
                timeout: 10s
                uri: http://authservice.istio-system.svc.cluster.local
  workloadSelector:
    labels:
      istio: ingressgateway

```

### Steps to Reproduce

I think this rule is very stupid. If I do it, I won't be able to use any other gateway in the cluster. I want to use ksvc but I won't be able to access it either. All of them have been redirected to http://authservice.istio-system.svc.cluster.local
