### ISSUE TITLE
NFS volume can't be attached

### ISSUE THREAD

**Issue by NJ3rsey** [kubeflow/manifests#3105]
### Validation Checklist

- [x] I confirm that this is a Kubeflow-related issue.
- [x] I am reporting this in the appropriate repository.
- [x] I have followed the [Kubeflow installation guidelines](https://github.com/kubeflow/manifests/blob/master/README.md).
- [x] The issue report is detailed and includes version numbers where applicable.
- [x] This issue pertains to Kubeflow development.
- [ ] I am available to work on this issue.
- [ ] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

master

### Detailed Description

Azure NFS persistent volume (file storage) can't be attached to the container to the personal directory unlike the Disk Storage. The Disk Storage has no that issue for some reason.

### Steps to Reproduce

1. Deploy any of KubeFlow version starting 1.8.0 with the default values on MS Azure AKS cluster
2. Use NFS File storage as a persistent volume to be attached to the container.

```yml
spawnerFormDefaults:
  workspaceVolume:
    readOnly: false
    value:
      mount: /home/jovyan
      newPvc:
        metadata:
          name: "{notebook-name}-workspace"
        spec:
          storageClassName: standard-azurefile
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce
```

3. Check if Jupiter Notebooks can be initiated: the error message is that Kernel (python) is not connected, hence the notebook is not working

---

Resolves by changing the mount path of the attached volume

```yml
spawnerFormDefaults:
  workspaceVolume:
    readOnly: false
    value:
      mount: /home/jovyan/pv
...
```
