### ISSUE TITLE
I want to set up an ip whitelist for istio because we only use it within the company

### ISSUE THREAD

**Issue by ZYWNB666** [kubeflow/manifests#3112]
### Validation Checklist

- [x] I confirm that this is a Kubeflow-related issue.
- [x] I am reporting this in the appropriate repository.
- [x] I have followed the [Kubeflow installation guidelines](https://github.com/kubeflow/manifests/blob/master/README.md).
- [x] The issue report is detailed and includes version numbers where applicable.
- [x] This issue pertains to Kubeflow development.
- [x] I am available to work on this issue.
- [ ] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

k8s version is 1.29.11
kubeflow version is 1.9.1

### Detailed Description

I want to set up an ip whitelist for istio. Since we only use it within the company, do you have any information to provide?

### Steps to Reproduce

This is what I wrote, but it seems not to have taken effect
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ingress-policy
  namespace: istio-system
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            ipBlocks:
              - 1.1.1.1
      to:
        - operation:
            hosts:
              - "kubeflow.osip.com"
  selector:
    matchLabels:
      app: istio-ingressgateway
```
I write like this. I think no one can access my domain name except for the ip 1.1.1.1, right?

We are very interested in the kubeflow product and look forward to receiving positive support
