### ISSUE TITLE
Update SeldonCore manifests to 0.4

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#315]
We need to update the SeldonCore manifests to 0.4.

There was an attempt to update the manifests in #273 

But this appeared to break the kubeflow/kubeflow E2E tests (see kubeflow/kubeflow#4001). 

So we rolled back the change to the seldon manifests in #312 

The break should have been caught by kubeflow/manifests presubmits but I suspect it wasn't because the presubmits aren't using the correct version of the manifests repo.

**Comment by jlewi** [comment]
kubeflow/manifests/issues/316 is why the presubmits didn't catch the break in the original PR.

**Comment by cliveseldon** [comment]
Does kfctl modify the manifests in any way? As there is no PersistenVolumeClaim in the file:

https://github.com/kubeflow/manifests/blob/76bd875d65d39960ab2d75daa2ba2b7a2a9e82a4/seldon/seldon-core-operator/base/seldon-operator-controller-manager-statefulset.yaml

The kustomize works on its own. What's the correct way to test with kfctl PRs to manifests repo so we can find what the issue is?

**Comment by cliveseldon** [comment]
I tested with master kfctl modified to print out what its creating and I see a VolumeClaimTemplate
```
{"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"labels":{"app.kubernetes.io/component":"seldon","app.kubernetes.io/instance":"seldon-core-operator","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"seldon-core-operator","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"v0.6","control-plane":"seldon-controller-manager","controller-tools.k8s.io":"1.0","helm.sh/chart":"seldon-core-operator-0.4.0"},"name":"seldon-operator-controller-manager","namespace":"kubeflow"},"spec":{"selector":{"matchLabels":{"app.kubernetes.io/component":"seldon","app.kubernetes.io/instance":"seldon-core-operator","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"seldon-core-operator","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"v0.6","control-plane":"seldon-controller-manager","controller-tools.k8s.io":"1.0"}},"serviceName":"seldon-operator-controller-manager-service","template":{"metadata":{"annotations":{"prometheus.io/scrape":"true"},"labels":{"app.kubernetes.io/component":"seldon","app.kubernetes.io/instance":"seldon-core-operator","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"seldon-core-operator","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"v0.6","control-plane":"seldon-controller-manager","controller-tools.k8s.io":"1.0"}},"spec":{"containers":[{"command":["/manager"],"env":[{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"SECRET_NAME","value":"seldon-operator-webhook-server-secret"},{"name":"AMBASSADOR_ENABLED","value":"true"},{"name":"AMBASSADOR_SINGLE_NAMESPACE","value":"false"},{"name":"ENGINE_CONTAINER_IMAGE_AND_VERSION","value":"docker.io/seldonio/engine:0.4.0"},{"name":"ENGINE_CONTAINER_IMAGE_PULL_POLICY","value":"IfNotPresent"},{"name":"ENGINE_CONTAINER_SERVICE_ACCOUNT_NAME","value":"default"},{"name":"ENGINE_CONTAINER_USER","value":"8888"},{"name":"ENGINE_LOG_MESSAGES_EXTERNALLY","value":"false"},{"name":"PREDICTIVE_UNIT_SERVICE_PORT","value":"9000"},{"name":"ENGINE_SERVER_GRPC_PORT","value":"5001"},{"name":"ENGINE_SERVER_PORT","value":"8000"},{"name":"ENGINE_PROMETHEUS_PATH","value":"prometheus"},{"name":"ISTIO_ENABLED","value":"true"},{"name":"ISTIO_GATEWAY","value":"kubeflow-gateway"}],"image":"docker.io/seldonio/seldon-core-operator:0.4.0","imagePullPolicy":"Always","name":"manager","ports":[{"containerPort":8080,"name":"metrics","protocol":"TCP"},{"containerPort":9876,"name":"webhook-server","protocol":"TCP"}],"resources":{"requests":{"cpu":"100m","memory":"20Mi"}},"volumeMounts":[{"mountPath":"/tmp/cert","name":"cert","readOnly":true}]}],"serviceAccountName":"seldon-manager","terminationGracePeriodSeconds":10,"volumes":[{"name":"cert","secret":{"defaultMode":420,"secretName":"seldon-operator-webhook-server-secret"}}]}},"volumeClaimTemplates":{"metadata":{"labels":{"app.kubernetes.io/component":"seldon","app.kubernetes.io/instance":"seldon-core-operator","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"seldon-core-operator","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"v0.6"}}}}}
```
Its appended at the end of the resource:
```
,"volumeClaimTemplates":{"metadata":{"labels":{"app.kubernetes.io/component":"seldon","app.kubernetes.io/instance":"seldon-core-operator","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"seldon-core-operator","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"v0.6"}}}}}
```
This is not in the original manifests. Could it be something to do with automatic handling of secrets?

**Comment by cliveseldon** [comment]
This is the offending yaml printed more nicely:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: seldon
    app.kubernetes.io/instance: seldon-core-operator
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: seldon-core-operator
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.6
    control-plane: seldon-controller-manager
    controller-tools.k8s.io: "1.0"
    helm.sh/chart: seldon-core-operator-0.4.0
  name: seldon-operator-controller-manager
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: seldon
      app.kubernetes.io/instance: seldon-core-operator
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/name: seldon-core-operator
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v0.6
      control-plane: seldon-controller-manager
      controller-tools.k8s.io: "1.0"
  serviceName: seldon-operator-controller-manager-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/component: seldon
        app.kubernetes.io/instance: seldon-core-operator
        app.kubernetes.io/managed-by: kfctl
        app.kubernetes.io/name: seldon-core-operator
        app.kubernetes.io/part-of: kubeflow
        app.kubernetes.io/version: v0.6
        control-plane: seldon-controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
      - command:
        - /manager
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SECRET_NAME
          value: seldon-operator-webhook-server-secret
        - name: AMBASSADOR_ENABLED
          value: "true"
        - name: AMBASSADOR_SINGLE_NAMESPACE
          value: "false"
        - name: ENGINE_CONTAINER_IMAGE_AND_VERSION
          value: docker.io/seldonio/engine:0.4.0
        - name: ENGINE_CONTAINER_IMAGE_PULL_POLICY
          value: IfNotPresent
        - name: ENGINE_CONTAINER_SERVICE_ACCOUNT_NAME
          value: default
        - name: ENGINE_CONTAINER_USER
          value: "8888"
        - name: ENGINE_LOG_MESSAGES_EXTERNALLY
          value: "false"
        - name: PREDICTIVE_UNIT_SERVICE_PORT
          value: "9000"
        - name: ENGINE_SERVER_GRPC_PORT
          value: "5001"
        - name: ENGINE_SERVER_PORT
          value: "8000"
        - name: ENGINE_PROMETHEUS_PATH
          value: prometheus
        - name: ISTIO_ENABLED
          value: "true"
        - name: ISTIO_GATEWAY
          value: kubeflow-gateway
        image: docker.io/seldonio/seldon-core-operator:0.4.0
        imagePullPolicy: Always
        name: manager
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 9876
          name: webhook-server
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /tmp/cert
          name: cert
          readOnly: true
      serviceAccountName: seldon-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: seldon-operator-webhook-server-secret
  volumeClaimTemplates:
    metadata:
      labels:
        app.kubernetes.io/component: seldon
        app.kubernetes.io/instance: seldon-core-operator
        app.kubernetes.io/managed-by: kfctl
        app.kubernetes.io/name: seldon-core-operator
        app.kubernetes.io/part-of: kubeflow
        app.kubernetes.io/version: v0.6
```
