### ISSUE TITLE
hack/get-test-targets is not able to pick files from configMapGenerator fields in kustomization.yaml

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/manifests#527]
/kind bug

Or could be a feature as well.

Related to: #413 

Example kustomization:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- files:
  - configuration.yaml
  name: some-configuration
- files:
  - other_configuration.yaml
  - some_script.sh
  name: some-other-resource
```

Currently, `make generate` or hack/get-test-targets picks files in a kustomization folder based on these `sed` commands:

https://github.com/kubeflow/manifests/blob/9e78376476d6377fd4194eaec77209dadb0dcd84/hack/gen-test-target.sh#L46

The commands here do not process the configMapGenerator file resources and do not generate the required resources in the unit-test file.

/cc @kkasravi 
/priority p2
