### ISSUE TITLE
kustomize syntax "env: params.env" deprecated in next release of kustomize; kubeflow stuck on kustomize 3.2.1

### ISSUE THREAD

**Issue by jbrette** [kubeflow/manifests#538]
Heads up, just learned the hard way:

the following syntax is not supported anymore (since 10/15/2019)

```yaml
configMapGenerator:
- env: params.env
  name: parameters
````

It needs to be:

```yaml
configMapGenerator:
- envs:
  - params.env
  name: parameters
```

Will have to enforce that the user uses a very specific version of kustomize until the manifests are updated.
