### ISSUE TITLE
Cross namespace ownership will cause resources to be GC'd; are we setting owner references for any cluster scoped resources?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#540]
@IronPan  pointed out the following potential issue to me

K8s garbage collection has the following requirements:
Cross-namespace owner references are disallowed by design. This means: 1) Namespace-scoped dependents can only specify owners in the same namespace, and owners that are cluster-scoped. 2) Cluster-scoped dependents can only specify cluster-scoped owners, but not namespace-scoped owners

Has any of our recent work with application work led us to violate this?

In particular are we setting owner references to cluster scoped resources like CRDs to namespace scoped resources; e.g. applications?

/assign @kkasravi

**Comment by kkasravi** [comment]
applications are not trying to claim cluster level resources, but I can verify by deploying kf

**Comment by jlewi** [comment]
@kkasravi I see; so just to double check; we are relying on the application controller to set owner references. We aren't doing it manually. So presumably the application controller should be adhering to appropriate policies when setting owner references.

So if the application controller was claiming cluster level resources in violation of K8s guidelines that would arguably be a bug in the application controller.

**Comment by kkasravi** [comment]
correct. For example here is jupyter's application
```
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: jupyter-web-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jupyter-web-app
      app.kubernetes.io/instance: jupyter-web-app-v0.7.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/component: jupyter-web-app
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v0.7.0
  componentKinds:
  - group: core
    kind: ConfigMap
  - group: apps
    kind: Deployment
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
  - group: rbac.authorization.k8s.io
    kind: Role
  - group: core
    kind: ServiceAccount
  - group: core
    kind: Service
  - group: networking.istio.io
    kind: VirtualService
  descriptor:
    type: jupyter-web-app
    version: v1beta1
    description: Provides a UI which allows the user to create/conect/delete jupyter notebooks.
    maintainers:
    - name: Kimonas Sotirchos
      email: kimwnasptd@arrikto.com
    owners:
    - name: Kimonas Sotirchos
      email: kimwnasptd@arrikto.com
    keywords:
     - jupyterhub
     - jupyter ui
     - notebooks
    links:
    - description: About
      url: https://github.com/kubeflow/kubeflow/tree/master/components/jupyter-web-app
    - description: Docs
      url: https://www.kubeflow.org/docs/notebooks
  addOwnerRef: true
```

Notice the addOwnerRef at the bottom and the lack of any cluster level resources listed in the componentKinds. If we were to add a cluster level resource like

```
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
```

it shouldn't claim it and I don't believe it does based on the reconcile loop -  it's watching in a namespace. But if it did it would be incorrect as you said.

Note that cluster level resources for jupyter-web-app carry the labels including the instance id which we need to use for kfctl delete. This PR hasn't been pushed yet - is it too late for 0.7 to get this in?
