### ISSUE TITLE
Get rid of KFDef kustomize magic?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#774]
Right now KFDef provides the following functionality

1. The ability to list a set of kustomize packages to be deployed
1. The ability to set parameters for each of those applications
1. The ability to combine multiple overlays like mixins (see [comment](https://github.com/kubeflow/kubeflow/issues/3490#issuecomment-579395304))

Could we get rid of this magic and rely more on straight kustomize.

* Per kubernetes-sigs/kustomize#171 I believe kustomize supports composition when each base package describes a distinct set of resources. So instead of listing kustomize packages in KFDef I think we could just define a new kustomize package with a kustomization.yaml that looked like

```...
bases:
- jupyter/notebook-controller/overlays/application
- jupyter/jupyter-web-app/overlays/application
```

A user could then just do

```
kustomize build to see all resources
```

Right now our overlays are structured such that we have multiple overlays (e.g. istio and application) which depend on base and then kfctl combines them. 

But we don't really need that magic. We could restructure our overlays so that they all use
what kustomize supports.

Along these lines we might want to rethink how we do parameter substitution to better leverage
https://github.com/kubernetes-sigs/kustomize/blob/master/examples/configGeneration.md

Can we structure it so that overriding parameters) would just be generating config map patches overlays in this package?

Related issues and threads:
kubeflow/kfctl#156
kubeflow/kubeflow#3490

**Comment by jlewi** [comment]
From a release stand point I think it could be very useful if we had overlays for each version e.g.
if we structured our kustomize apps 

```
bases
  ...
overlays
   master
     ...
    v1.0.0
    v1.1.0
```

v1.1.0 could  potentially use v1.0.0 as its base.

One of the motivations here is to reduce the cost of maintaining release branches.

Right now there is a bunch of work that needs to be done to update the release branch for each application e.g.
  1. Bump the version in the Application CR
  1. Update the docker image

Right now we make these changes in the base package.

That means we can't make these changes until we cut a release branch. This means its hard to simultaneously 

* Start preparing the application for the release
* Continue to fix bugs

If we use overlays for the version then we can start checking that into master and easily keep it in sync as fixes to the underlying base deployment go in.

**Comment by SebBlin** [comment]
The magic feature of having multiple overlays and combining them is a **"really great feature"** and should be kept.
I use it to build my own repo that contain all my personnal customization to apply during the deployment process.

Here is an exemple below for Dex : 
Currently Dex is able to delegate authentication to an external OIDC IDentity Provider and this is something I want to use, but this IDP is behind a forward proxy so I need to update the dex container configuration to add env variables to configure http_proxy. In addition, this IDP is secured with a private CA that I need to add in the Dex container (I had to rebuild my own dex container); so I need to upate the name of dex image to load. At last, the Dex parameters in KFDef currently don't support configuring an OIDC provider, it can be done by updating the dex config-map. 

With few files in my repo /my-manifests/dex/overlays/my-overlay I can achieve a very custumized deployement (even customizations that are not pre-configurable) and I stil benefit form the standards manifests without duplicating them ! 

Here is the content of my overlay 
/my-manifests/dex/overlays/my-overlay
    config-map.yaml # the new content of the config map with my OIDC configuration
    deployment.yaml # the patch of the Deployment to just add 'envFrom: Proxies' to the dex container
    kustomization.yaml # the update for the name of dex image to point to my private registry

Here is the content of my KFDef (extracts) 
```
apiVersion: kfdef.apps.kubeflow.org/v1beta1
kind: KfDef
metadata:
  name: MyKubeflow
  namespace: kubeflow
spec:
  applications:
[ ... ]
  - kustomizeConfig:
      overlays:
        - istio
      parameters:
        - name: namespace
          value: auth
          [ ... Other dex parameters ... ]
      repoRef:
        name: manifests
        path: dex-auth/dex-crds
    name: dex
  - kustomizeConfig:
      overlays:
        - my-overlay
      repoRef:
        name: my-manifests
        path: dex
    name: dex
  [ ... ]
  repos:
  - name: manifests
    uri: https://codeload.github.com/kubeflow/manifests/tar.gz/v0.7-branch
  - name: my-manifests
    uri: https://mygitserver.example.com/kubeflow/kubeflow-manifests/-/archive/master/kubeflow-manifests-master.tar.gz
  version: master
```

This is just an exemple for one component but I also use this for others. 
Currently, combining is not always working exactly the I would like it to work (and I have to workaround); but, please, keep it and improve it.
