### ISSUE TITLE
loadBalancerScheme is not replaced in ingress annotation

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/manifests#946]
Platform: AWS
Branch: master

This is bug from https://github.com/kubeflow/manifests/pull/653, 
`loadBalancerScheme` was introduced in the base manifest but there's no params.yaml for base and annotation doesn't get updated. no-auth `kfctl_aws.yaml` is affected. 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/scheme: $(loadBalancerScheme)
```
