### ISSUE TITLE
MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the server could not find the requested resource

### ISSUE THREAD

**Issue by tomalbrecht** [kubeflow/manifests#959]
Since several days I am not able to deploy kubeflow 1.0 on a clean microk8s install. The Istio-pods won't come up anymore. Can anyone help me with this issue?

## Steps to reproduce:

1. fresh microk8s install (1.14/1.15 produce the same results) as root (sudo): <br>
```
snap remove microk8s
rm -rf $HOME/.kube
snap install microk8s --classic --channel=1.14/stable
microk8s.status --wait-ready
microk8s.enable dns dashboard storage
microk8s.enable gpu
```
2. download kfctl (rc3/1.0.0 produce the same results) as root (sudo):<br>
```
export CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml"
#export CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_istio_dex.v1.0.0.yaml"
#export CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/b37bad9eded2c47c54ce1150eb9e6edbfb47ceda/kfdef/kfctl_existing_arrikto.0.7.1.yaml"
kfctl apply -V -f ${CONFIG_FILE}
```
3. wait and check - Istio containers won't come up
```
kubectl get pods -n istio-system
```
--> results in status 'Container Creating' for:
* istio-telemetry
* istio-policy
* istio-pilot
* istio-ingressgateway

In kubernetes-dashboard I can en error under "Workloads->Deployments->istio-ingressgateway"

> MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the server could not find the requested resource

same error for: istio-pilot. The other containers seem to wait for these two containers.

## Additional Information

CONFIG_URIs used:
* https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
* https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_istio_dex.v1.0.0.yaml
* https://raw.githubusercontent.com/kubeflow/manifests/b37bad9eded2c47c54ce1150eb9e6edbfb47ceda/kfdef/kfctl_existing_arrikto.0.7.1.yaml

```kfctl version: ```
> kfctl v1.0-0-g94c35cf (but same problem with older versions)

```microk8s.kubectl version```

> Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:41:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:32:32Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

```istio-ingressgateway-68875ff4cd```
> gcr.io/istio-release/proxyv2:release-1.3-latest-daily

```lsb_release -a```

>No LSB modules are available.
>Distributor ID: Ubuntu
>Description:    Ubuntu 18.04.4 LTS
>Release:        18.04
>Codename:       bionic

```kubectl describe pods -n istio-system >describe-istio-system.txt```
[describe-istio-system.txt](https://github.com/kubeflow/manifests/files/4261789/describe-istio-system.txt)

I also tried to disable Istio and enable Istio from microk8s as mentioned [here](https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/). Without success (other errors will occur)

> Disabling istio installation - If your Kubernetes cluster has an existing Istio installation you may choose to not install Istio by removing the applications istio-crds and istio-install in the configuration file kfctl_k8s_istio.v1.0.0.yaml

**Comment by krishnadurai** [comment]
@tomalbrecht Seems like your micro-k8s hasn't added extra configurations in Kubernetes API configuration for enabling trustworthy JWT.

The documentation for kfctl-istio-dex.yaml states this in the section:
https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/#before-you-start

Here's Istio's blog which will help you set up these API flags:
https://istio.io/blog/2019/trustworthy-jwt-sds/

**Comment by tomalbrecht** [comment]
@krishnadurai Thanks for your help. 

I am not sure if I understand this. I did not change my microk8s installation - I use the same stable Kubernetes 1.14 version (microk8s) since several weeks. Nor I was using an older version. What did change is the kubeflow.yaml. Shouldn't this be done by the kubeflow deployment if it needs it?

However, I tried to follow your mentioned blog entry. I don't have a clue where to change what configuration. I used this (amongst others) yaml for my deployment of kubeflow https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml

**Comment by krishnadurai** [comment]
@tomalbrecht 
You might want to set values to these flags:
```
    --service-account-issuer
    --service-account-signing-key-file
    --service-account-api-audiences
```
Refer: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection

In your`kube-api.yaml` config usually lies in `/etc/kubernetes/manifests/kube-apiserver.yaml`
```
spec:
  containers:
  - command:
    - kube-apiserver
```

Since this is a Kubernetes API server flag, it won't be set by Kubeflow's installer.

**Comment by tomalbrecht** [comment]
@krishnadurai: Thanks again,  :-)

I must say, that I am a beginner in Kubernetes (still doing a course) and did not find a tutorial for changing these parameters. So thank you for your patience.

I found the right file: `/var/snap/microk8s/current/args/kube-apiserver` and edited it (messed it up to be exact). When I restart the server (`microk8s.stop`and `microk8s.start`) the api-server won't come up again. I cannot figure out what kind of values I'd have to set. I read the link for my specific 1.14 version(https://v1-14.docs.kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/ and this one https://v1-14.docs.kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/. There is not flag called `--service-account-api-audiences`. The other flags are mentioned.

```
--cert-dir=${SNAP_DATA}/certs
--service-cluster-ip-range=10.152.183.0/24
--authorization-mode=AlwaysAllow
--basic-auth-file=${SNAP_DATA}/credentials/basic_auth.csv
--enable-admission-plugins="NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota"
--service-account-key-file=${SNAP_DATA}/certs/serviceaccount.key
--client-ca-file=${SNAP_DATA}/certs/ca.crt
--tls-cert-file=${SNAP_DATA}/certs/server.crt
--tls-private-key-file=${SNAP_DATA}/certs/server.key
--kubelet-client-certificate=${SNAP_DATA}/certs/server.crt
--kubelet-client-key=${SNAP_DATA}/certs/server.key
--secure-port=16443
--token-auth-file=${SNAP_DATA}/credentials/known_tokens.csv
--etcd-servers='https://127.0.0.1:12379'
--etcd-cafile=${SNAP_DATA}/certs/ca.crt
--etcd-certfile=${SNAP_DATA}/certs/server.crt
--etcd-keyfile=${SNAP_DATA}/certs/server.key

--service-account-issuer
--service-account-signing-key-file==${SNAP_DATA}/certs/server.key
--service-account-api-audiences

--requestheader-client-ca-file=${SNAP_DATA}/certs/ca.crt
```

Can you or someone else referent to a link which values to set, please? I am not able to connect this information yet.

**Comment by nepalineupane** [comment]
I am also wondering what should be the values to these flags? I see all pods under istio-system have their own service accounts on running -- kubectl get sa -n istio-system.

    --service-account-issuer
    --service-account-signing-key-file
    --service-account-api-audiences

**Comment by nepalineupane** [comment]
@tomalbrecht, may be you can check if the following paths work for you. 

- --service-account-signing-key-file=/etc/kubernetes/pki/sa.key
- --service-account-key-file=/etc/kubernetes/pki/sa.pub
- --service-account-issuer=api
- --service-account-api-audiences=api,vault,factors

**Comment by nepalineupane** [comment]
@tomalbrecht, may be you can check if the following paths work for you.

--service-account-issuer=api
--service-account-signing-key-file=${SNAP_DATA}/certs/server.key
--service-account-api-audiences=api

FYI: https://github.com/linkerd/linkerd2/issues/3260

**Comment by nepalineupane** [comment]
I am having similar problem after updating kubeflow 0.7 to kubeflow 1.0. I haven't been able to solve it yet. I still have istio pods stuck in ContainerCreating stage. 

I went through this https://jpweber.io/blog/a-look-at-tokenrequest-api/ and change values accordingly, but its not working.

**Comment by tomalbrecht** [comment]
@nepalineupane: Thank you! I'll try this out. 

I got 1.0rc4 working about 6 days ago. The problems started the same time when they pinned the manifest to a specific version. Not sure yet, how to get the older version. As soon I figure it out, I'll test it.

https://github.com/kubeflow/manifests/commit/f56bb47d7dc5378497ad1e38ea99f7b5ebe7a950

**Comment by tomalbrecht** [comment]
@nepalineupane @krishnadurai 

**I  set values to these kube-apiserver flags according to your posts** https://github.com/kubeflow/manifests/issues/959#issuecomment-591992935) and (https://github.com/kubeflow/manifests/issues/959#issuecomment-592255738.

```sudo vi /var/snap/microk8s/current/args/kube-apiserver```

and added these configs
>  --service-account-issuer=api
> --service-account-signing-key-file=${SNAP_DATA}/certs/server.key
> --service-account-api-audiences=api

then i restarted the cluster:
```
sudo microk8s.stop
sudo microk8s.start
```

after this I deployed kubeflow ([see](https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/)) using:
```CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml"```

Same problem as before. Istio won't come up. This time with different errors.

> MountVolume.SetUp failed for volume "clusterlocalgateway-certs" : couldn't propagate object cache: timed out waiting for the condition
> Readiness probe failed: HTTP probe failed with statuscode: 503

> MountVolume.SetUp failed for volume "istio-certs" : couldn't propagate object cache: timed out waiting for the condition
> Liveness probe failed: Get http://10.1.1.154:15014/version: dial tcp 10.1.1.154:15014: connect: connection refused
> Back-off restarting failed container

**Comment by tomalbrecht** [comment]
Trying an older CONFIG_URI did not work out either.

```CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml"```

> MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the server could not find the requested resource
> (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "81e6ef799f2661cd2680f77974bb33c9806ff02c3e834c1da3888749ebb32aa5": failed to allocate for range 0: no IP addresses available in range set: 10.1.1.1-10.1.1.254

**Comment by tomalbrecht** [comment]
Old 0.7 kubeflow version with kfctl v0.7.1-2-g55f9b2a is deploying.

CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/e7e7145e9cf735fe2f529f59bb9a932d9ef3b02a/kfdef/kfctl_istio_dex.v1.0.0.yaml"

**Comment by tomalbrecht** [comment]
Old 0.7.1 version does work (using kfctl v1.0-rc.3-1-g24b60e8) with a little workaround for deployment.

`CONFIG_URI=https://raw.githubusercontent.com/kubeflow/manifests/b37bad9eded2c47c54ce1150eb9e6edbfb47ceda/kfdef/kfctl_existing_arrikto.0.7.1.yaml`

**Comment by eduardovelludo** [comment]
I'm having exactly the same problem.
My cluster is on EC2 and it was created using Kops. I'll try to use the old version like you suggested

**Comment by vaskokj** [comment]
I've got a Kubespray deployment thats about a month old, 0.7.1 worked, 1.0.0 doesn't and gives this error.

**Comment by nepalineupane** [comment]
> Old 0.7.1 version does work (using kfctl v1.0-rc.3-1-g24b60e8) with a little workaround for deployment.
> 
> `CONFIG_URI=https://raw.githubusercontent.com/kubeflow/manifests/b37bad9eded2c47c54ce1150eb9e6edbfb47ceda/kfdef/kfctl_existing_arrikto.0.7.1.yaml`

Hope we can get inputs to make the newer version work.

**Comment by DanaHan** [comment]
Same Porblem. I also try microk8s 1.17 version. No luck. I also try to replace kfctl 0.7 version istio  yaml files into kfctl V1.0.0. All pods work well. But when I try to accesss dashboard. Jupyter web service and some other service can not load. So It seems that the  kfctl_istio_dex.v1.0.0.yaml has errors. Any help?

**Comment by krishnadurai** [comment]
@tomalbrecht Here's some more help in configuring:

This is the configuration for my kubeadm installed on-premise cluster in the file `/etc/kubernetes/manifests/kube-apiserver.yaml`:

```
spec:
  containers:
  - command:
    - kube-apiserver
    - --advertise-address=10.30.118.172
    - --allow-privileged=true
    - --authorization-mode=Node,RBAC
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --enable-admission-plugins=NodeRestriction
    - --enable-bootstrap-token-auth=true
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
    - --etcd-servers=https://127.0.0.1:2379
    - --insecure-port=0
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --requestheader-allowed-names=front-proxy-client
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
    - --secure-port=6443
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --service-cluster-ip-range=10.96.0.0/12
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    - --service-account-signing-key-file=/etc/kubernetes/pki/sa.key
    - --service-account-issuer=kubernetes.default.svc
```

Note my settings for flags:

```
    - --service-account-signing-key-file=/etc/kubernetes/pki/sa.key
    - --service-account-issuer=kubernetes.default.svc
```

I'll try and get my hands on a micro-k8s server and see what these values can be for it.
