### ISSUE TITLE
Profiles deployment has missing port

### ISSUE THREAD

**Issue by svilenvul** [kubeflow/manifests#976]
We have installed Kubeflow with the vanilla deployment configuration in the cluster and we have setup Istio routing to it with SDS. After this we got an error in the UI ("Unable to contact Profile Controller").

The access to the `profiles-kfam.kubeflow` service was blocked. I found out that there is no `ports` section in the profiles deployment. When I added the following snippet the problem was resolved:

```
spec:
  ...
  template:
    ...
    spec:
      ...
      containers:
      - name kfam
        ports:
        - containerPort: 8081
          name: kfam-http
          protocol: TCP

```
